### ISSUE TITLE
Unrecognized Connect with code S15

### ISSUE THREAD

**Issue by kvanisterdael** [duncan3dc/sonos#100]
Just had the case where a Connect was not recognized by the library, because it had code S15 (instead of ZP90).

**Comment by duncan3dc** [comment]
Hi @kvanisterdael, I'll get support for this new version of the CONNECT added soon

**Comment by duncan3dc** [comment]
This is fixed in version [2.0.7](https://github.com/duncan3dc/sonos/releases/tag/2.0.7)
