### ISSUE TITLE
New Sonos One and Ethernet

### ISSUE THREAD

**Issue by Jmi91** [duncan3dc/sonos#103]
Hi,
I have a problem when my new Sonos One (S18) is connected by ethernet cable: It is never found.
It's working when the Sonos ONE is using wireless SonosNet.
Thank you.
Regards.

Jmi

**Comment by duncan3dc** [comment]
Hi Jmi, can you [turn on logging](http://duncan3dc.github.io/sonos/setup/logging/) and post the results to a gist then link them here?

**Comment by Jmi91** [comment]
I have a problem with installing monolog and turn on logging.
I have done that:

composer require monolog/monolog
composer require php-console/php-console

but I have this error in my code:

PHP Fatal error:  Uncaught Error: Class 'Monolog\Logger' not found

Any idea ?

**Comment by Jmi91** [comment]
Here is the gist link:

https://gist.github.com/Jmi91/94a78590e66d68e44c8abf5bfc3f6dbf

**Comment by Jmi91** [comment]
Another example:
https://gist.github.com/Jmi91/b353eac6b19135488c997af5a7f88be6

**Comment by duncan3dc** [comment]
@Jmi91 Sorry for the delay here, from those logs it looks like the speaker is found successfully.
As for the groupings, are you doing them via this library or another source? You may need to disable caching (or use a shorter cache time) if you need to make changes to groupings via another source (eg the Sonos app)
