### ISSUE TITLE
IKEA Symfonisk players

### ISSUE THREAD

**Issue by kvanisterdael** [duncan3dc/sonos#104]
The new IKEA players have model types that are not yet recognized by the isSpeaker() method.

Bookshelf model: S21
Lamp model: ???

**Comment by Liver64** [comment]
Lamp = S20

**Comment by duncan3dc** [comment]
Thanks to both of you for providing these, they're available in [2.1.0](https://github.com/duncan3dc/sonos/releases/tag/2.1.0) now
