### ISSUE TITLE
Sonos Events

### ISSUE THREAD

**Issue by LeonAlexanderBartz** [duncan3dc/sonos#108]
Hello there,
Is there any way to get the events of a speaker like 'Play',
wich where triggered by another device ?
I don't want to use a for loop.

**Comment by duncan3dc** [comment]
Hi @LeonAlexanderBartz, sorry for the lack of response here!
It is possible, and I was doing some work on it a while ago, but nothing production ready yet I'm afraid.
You can see my initial hacking on the [subscriptions branch](https://github.com/duncan3dc/sonos/compare/subscriptions?expand=1) if you want to give it a go
