### ISSUE TITLE
Empty room returned by getControllers()

### ISSUE THREAD

**Issue by tomsommer** [duncan3dc/sonos#109]
```
$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
    echo "{$controller->room} = " . $controller->getStateName() . "\n";
}

```

return
`
 = STOPPED
`

This breaks getControllerByRoom() 

Log: https://pastebin.com/qnydDJiL

Gruping in UI:

![image](https://user-images.githubusercontent.com/149171/78509984-4e407880-7792-11ea-952f-3d997cbc2810.png)

**Comment by dutchie027** [comment]
@tomsommer you can't call  `room` by the private method in the 2.0 version. You'd need to change the code to be:

`echo $controller->getRoom() . " = " . $controller->getStateName() . "\n";`

**Comment by duncan3dc** [comment]
Hi @tomsommer, what version are you using?
If you're on a recent version please [enable logging](http://duncan3dc.github.io/sonos/setup/logging/) and run your script again then paste the output here or in a gist and I will investigate
