### ISSUE TITLE
feature request TTS

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#11]
i use TTS command on SONOS of DjMomo/sonos
this code is a good solution in automatinghousesystem for played alarm or everything. It was perfect if you add in your code

**Comment by 889laurent** [comment]
is this the right solution to open issues for my requests ?
or is it you use the email ?

**Comment by duncan3dc** [comment]
This is the right solution :+1:

**Comment by patrickharris** [comment]
Yes, this would be great to add. Might you add this Duncan? If not, I might have a go myself.

**Comment by duncan3dc** [comment]
@patrickharris I plan to take a look at some point, but if you want to give it a go, be my guest

**Comment by 889laurent** [comment]
i added this code
''' protected function CutString($string,$intmax)
	{
		$i = 0;
		while (strlen($string) > $intmax)
		{
			$string_cut = substr($string, 0, $intmax);
			$last_space = strrpos($string_cut, "+");
			$strings[$i] = substr($string, 0, $last_space);
			$string = substr($string, $last_space, strlen($string));
			$i++;
		}
		$strings[$i] = $string;
		return $strings;
	}
  public function TTSToMp3($words,$lang)
	{
		// Directory
		$folder = "audio/".$lang;
		// Replace the non-alphanumeric characters
		// The spaces in the sentence are replaced with the Plus symbol
		$words = urlencode($words);
		// Name of the MP3 file generated using the MD5 hash
		$file = md5($words);
		// If folder doesn't exists, create it
		if (!file_exists($folder))
			mkdir($folder, 0755, true);
		// Save the MP3 file in this folder with the .mp3 extension
		$file = $folder."/TTS-".$file.".mp3";
		// If the MP3 file exists, do not create a new request
		if (!file_exists($file))
		{
			// Google Translate API cannot handle strings > 100 characters
			$words = $this->CutString($words,100);
			ini_set('user_agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0');
			$mp3 = "";
			for ($i = 0; $i < count($words); $i++)
				$mp3[$i] = file_get_contents('http://translate.google.com/translate_tts?q='.$words[$i].'&tl='.$lang);
			file_put_contents($file, $mp3);
		}
		return $file;'''
I then inserts the file created in the queue
'''$directory = "192.168.0.108/Partage/duncan/";
$message = $_GET['message'];
//$message ="bonjour";
$volume2 = $_GET['volume'];
$lang = "fr";
$filetts = $controller->TTSToMp3($message,$lang);
//echo $filetts;
$queue = $controller->getQueue();
$state = $controller->getStateDetails();
$postrack = $state->queueNumber;
//echo "position dans la queue avant:" . $postrack . "\n";
$queue->addTrack("x-file-cifs://" .$directory . $filetts ); 
$numberOfTracks = count($queue);
$controller->selectTrack($numberOfTracks) ;
//echo "Position dans la queue: " . $state->queueNumber . " sur " . $numberOfTracks . "\n";
$controller->setvolume($volume2);
$controller->play(); 
sleep(2);
$controller->pause();
$queue->removeTrack($numberOfTracks-1); 
$controller->selectTrack($postrack) ;'''
this solution works fine

**Comment by patrickharris** [comment]
I'm working on this too. Is the best thing to commit new code to a git branch? 

djmomo's method of waiting for the included track to finish (@889laurent - you have hard coded a time there instead) was to see if the track number had dropped from the queue, but I'm not sure whether this method will currently work with dauncan's code.

**Comment by 889laurent** [comment]
The last song in the list is read and then she stops if the random function is not activate


Laurent MARIO Directeur Technique

  [cid:logo2015020ae1]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture19efae3]                                                                                                      [cid:devdurable8b9e90]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 19 mars 2015 à 20:24, patrickharris <notifications@github.com<mailto:notifications@github.com>> a écrit :


I'm working on this too. Is the best thing to commit new code to a git branch?

djmomo's method of waiting for the included track to finish (@889laurent<https://github.com/889laurent> - you have hard coded a time there instead) was to see if the track number had dropped from the queue, but I'm not sure whether this method will currently work with dauncan's code.

**Comment by duncan3dc** [comment]
@patrickharris Yes please commit to a branch and submit a pull request when you have a working feature, thanks

**Comment by 889laurent** [comment]
I dont know how?
I find

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo2015f43acc]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture116d653]                                                                                                      [cid:devdurable419649]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 20 mars 2015 à 00:51, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


@patrickharris<https://github.com/patrickharris> Yes please commit to a branch and submit a pull request when you have a working feature, thanks

**Comment by duncan3dc** [comment]
I've done some initial work on this in a branch, you can install and test it out like so:
```
composer require duncan3dc/sonos:dev-text-to-speech
```

```php
use duncan3dc\Sonos\Directory;
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Tracks\TextToSpeech;

require __DIR__ . "/vendor/autoload.php";

$sonos = new Network;

$directory = new Directory("/var/shares/sonos", "SERVERNAME/sonos", "tts");
$track = new TextToSpeech("Testing text to speech", $directory);

$controller = $sonos->getControllerByRoom("Living Room");

$controller->getQueue()
    ->clear()
    ->addTrack($track);

$controller
    ->setRepeat(false)
    ->play();
```

**Comment by patrickharris** [comment]
Hey, that's great you've done some work on this. The way I did this was by interrupting any current track or stream for the speech, and then continuing the current track or stream after the speech was finished. Nearly all my code was dumped in one class called 'speech' (because I thought this was the only place this kind of interrupt would be required). It also did weather forecasting. I could either push up the speech class for you to have a look at, or extrapolate the stuff out a bit. 

Would it be possible to remove the reliance on php-soap? I can't install this on my NAS, only on my computer.

**Comment by duncan3dc** [comment]
Thanks @patrickharris, that's pretty much exactly what I did: https://gist.github.com/duncan3dc/e73734297a04c3ba4002

If you push your work up to a branch I'll take a look. I'm not sure if this code belongs in this Sonos library yet.

I'm thinking just an `exportState()` method to extract the current queue and playing position, then a `restoreStore()` method to set the queue and playing position again. So that the code in the gist is easier to do, but as you said this might be redundant if it's only ever used for the same 'interrupt' functionality all the time.

I doubt it would be feasible to remove the php-soap stuff, but if you open a separate ticket for that I'll give it a look.

**Comment by patrickharris** [comment]
Ahh - I hadn't seen that weather link, and the "clear queue" got me confused - I hadn't realised you had stored the tracks before clearing. That's really nice and clean! Does it restore a stream correctly? I found I had to interrupt a stream differently to a track. Also, I was able to restore a stream url (audio), but couldn't successfully restore the stream text and graphic (i.e. title, artist, etc), because I didn't know what the original info was.

**Comment by duncan3dc** [comment]
No I haven't tackled stream support yet, and the spotify also has the same issue you mentioned there (no artist, title, etc)

**Comment by duncan3dc** [comment]
I've added the exporting/restoring state methods now to make it easier to 'interrupt' playing.

Do you both think this is enough for TTS support? (cc: @889laurent)

```php
use duncan3dc\Sonos\Directory;
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Tracks\TextToSpeech;

require __DIR__ . "/vendor/autoload.php";

$sonos = new Network;

$directory = new Directory("/var/shares/sonos", "SERVERNAME/sonos", "tts");
$track = new TextToSpeech("Testing text to speech", $directory);

$controller = $sonos->getControllerByRoom("Living Room");

$state = $controller->exportState();

$controller
    ->getQueue()
    ->clear()
    ->addTrack($track);

$controller
    ->setRepeat(false)
    ->play();

echo "waiting.";
while (true) {
    sleep(1);
    echo ".";
    if ($controller->getState() !== Controller::STATE_PLAYING) {
        echo "\n";
        break;
    }
}

$controller->restoreState($state);
```

**Comment by patrickharris** [comment]
Hey that looks fantastic. I'll test it when I get home. But it would be good if it can 'restoreState' a stream (as well as track).

**Comment by duncan3dc** [comment]
Yeh I'll add that before releasing, just making sure the api is sensible first

**Comment by 889laurent** [comment]
i test the tts and it works find on my sonos. i not tried the restorestate

**Comment by 889laurent** [comment]
i test the tts and it works fine on my sonos but i not tried the restorestate . I test when i get home

thanks

**Comment by patrickharris** [comment]
It would be good to be able to alter the tts url and language, as for instance, the .co.uk has an English accent, as opposed to the .com. Also, could allow for more than 100 characters by combining multiple files. I found by looking for a fullstop/period before the 100 character maximum, and chopping there, I got better inflexion than chopping at the nearest space.

**Comment by patrickharris** [comment]
I rebooted all the network devices today, and now it suddenly works. Thanks guys for your help!!!

**Comment by patrickharris** [comment]
I tested it - it works well. However, I get an "Fatal error: Class 'Controller' not found", so I have to replace "Controller::STATE_PLAYING" with "202".

Restore state worked for a track, except it did not replace the artwork. The TTS needs an ability to give a temporary volume it can interrupt with, and restore state should include restoring the previous volume. Anyway, great work - it's fantastic to have this in!

**Comment by patrickharris** [comment]
The caching doesn't seem to be working properly. When I rebooted my system, the IP changed for the sonos speaker. I could only access it by creating a "new Network(new \Doctrine\Common\Cache\ArrayCache)". However if I later ever request "new Network" (i.e. with cache), then the old IP is used, resulting in an error. I assume the initial cache is never overwritten.

**Comment by patrickharris** [comment]
Argh, something else. After the tts file plays, and the interrupted track stops, the url of the tts file is displayed, and then played next. It seems to not be removed, or to be added, to the replaced state queue. If a track isn't playing, the tts breaks, but this is because you haven't done the 'interrupt stream state' yet.

**Comment by duncan3dc** [comment]
@patrickharris It's difficult to respond to multiple questions/comments inside a single issue, please log them separately in future.

TTS is still in development, so there are likely to be many issues with it before it is put into a proper release. I appreciate you testing it out and I will let you know when it's ready for that level of feedback, as mentioned above I was just trying to get your opinion on the API, the version in that branch is just a quick and dirty attempt at an example of how it will work.

As for the cache, you are correct, by default it uses a long-lived cache, you can see some examples of how to use one that you can clear on demand [in the docs](http://duncan3dc.github.io/sonos/setup/)

**Comment by patrickharris** [comment]
Thanks for the cache link.

**Comment by patrickharris** [comment]
I think the idea of export and restore makes sense, but only if you decide never to interrupt a tts with another. I guess concurrent tts requests would get added to the current queue, at the end of which, the initial state would be restored.

**Comment by 889laurent** [comment]
i think is more better if you give possibility to choose the language in your api with variable !

**Comment by 889laurent** [comment]
i think is more better if the state of controller volume is saved

**Comment by duncan3dc** [comment]
The controller doesn't have a volume, speakers that it controls do, but I'll give it some thought

**Comment by duncan3dc** [comment]
Almost there guys, and I think I will add an `interupt()` method to handle the backup/restore common case.

Just need to handle streams and then it should be ready for release, I'll update this issue again when it's ready for testing. Thanks

**Comment by duncan3dc** [comment]
OK the 1.2 branch has been updated now, I think I've covered everything you've mentioned. I'd be grateful if you give it a test and see if there's anything I've missed before I release it.

I've updated the [gist](https://gist.github.com/duncan3dc/e73734297a04c3ba4002) to use the new `interrupt()` method, so you don't need to manually backup state and sleep, etc.

Thanks for your help with this

**Comment by 889laurent** [comment]
good morning, thanks for your job. I test tts on play 1,3 connect amp , connect and play bar. There are error with play bar when numerical input on tv is on ('UPnPError: 701'). The interupt function is ok. i dont find how play in "fr" lang ?

**Comment by duncan3dc** [comment]
Thanks for the feedback @889laurent I'm just finishing up the documentation and then I will tag a new release.

You can set the language (as well as the google domain) on the `TextToSpeech` object after you create it:
```php
$track = new TextToSpeech($message, $directory);
$track->setLanguage("fr");
$track->setTopLevelDomain("fr");
```
All of those methods are chainable:
```php
$track = (new TextToSpeech($message, $directory))
    ->setLanguage("fr")
    ->setTopLevelDomain("fr");
```

**Comment by 889laurent** [comment]
thanks and ok for fr .

**Comment by 889laurent** [comment]
if y want to play "interrupt track" with special volume , please help me with the best method

**Comment by 889laurent** [comment]
if i want to play with special volume, i used this code
$v = $sonos->getControllerByRoom("Salon TV")->getVolume();
$sonos->getControllerByRoom("Salon TV")->setVolume(100)->interrupt($track)->setVolume($v);

its better if they are include in interrupt function

**Comment by duncan3dc** [comment]
@889laurent It is already available in the `interrupt()` method, please wait for the documentation/release

**Comment by 889laurent** [comment]
sorry i wait

**Comment by duncan3dc** [comment]
No problem @889laurent I like your eagerness. I will try and release tonight

**Comment by 889laurent** [comment]
i find alone   interrupt($track, $volume=100)  im happy

**Comment by duncan3dc** [comment]
Version 1.2.0 has just been released
