### ISSUE TITLE
Group not listed as controller

### ISSUE THREAD

**Issue by christianschneider89** [duncan3dc/sonos#110]
Hello

I have the following php code:

```
	echo 'Controller count: '.count($controllers);
	echo "\n\n";
	foreach ($controllers as $controller)
	{	
		echo $controller->getName().' '.$controller->getRoom();
		echo "\n";
	}
	echo 'End of list';
```

My sonos desktop app shows:
![image](https://user-images.githubusercontent.com/15085873/94468456-bbbee600-01c4-11eb-9025-543985125647.png)

But the output from the script shows me:
```
Controller count: 1

192.168.0.28 - Sonos Play:5 Atelier
End of list
```

What could be the problem?

Thanks
Chris

**Comment by dutchie027** [comment]
@christianschneider89 I think what you're looking for is the speaker class not the controller class aren't you?

What happens if you use:

```
<?php

require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;

#$logger = new \Monolog\Logger("sonos");
#$handler = new \Monolog\Handler\StreamHandler("php://stdout", \Monolog\Logger::DEBUG);
#$logger->pushHandler($handler);

$sonos = new Network();
$speakers = $sonos->getSpeakers();

foreach ($speakers as $speaker) {
	print $speaker->getName() . " " . $speaker->getRoom() . "\n";
}
```

**Comment by christianschneider89** [comment]
@dutchie027 Thanks for your reply.

My plan was to get an overall status of my sonos (if only one speaker is playing the status should be true).
The speaker class don't have a getState() method, so I was using the controller class.

I don't know why, but I just tested it again. At the moment with the same code (see initial post) and same groups both controllers are appearing in the output:

```
Controller count:2

192.168.0.26 - Sonos Connect:Amp Büro
192.168.0.28 - Sonos Play:5 Atelier
End of list
```

Chris
