### ISSUE TITLE
Documentation uses private method

### ISSUE THREAD

**Issue by dutchie027** [duncan3dc/sonos#111]
On your [documentation](http://duncan3dc.github.io/sonos/usage/alarms/) you suggest getting the room by using

`$alarm->getSpeaker()->room`

however room is private and you would really need to get the room name by using:

`$alarm->getSpeaker()->getRoom()`

**Comment by duncan3dc** [comment]
Sorry I must have missed that when preparing the docs for 2.0, I will correct it soon, thanks for raising the issue!
