### ISSUE TITLE
multiroom playing sync: simple question

### ISSUE THREAD

**Issue by vespino** [duncan3dc/sonos#112]
Before I go out and buy a number of Sonos speakers... I was hoping to utilize this project for one simple task which is schedule playback of internet streams on the 3 Sonos speakers I'm planning to buy, 2 of which will be in the same room, so it's important playback will be in sync. I don't like to do repetitive tasks, that is why I automate things. Start playing at 7.15am, change the channel at 9, back to the original channel at 10, play certain stations on certain times of the week, etc.

This is just one of the many features of this project, correct? Not scheduling itself, but tell Sonos to play (or stop) something, I already have the schedule from my previous set of speakers.

I always never use my personal music library or Spotify, but in case I wanted to use Spotify I will probably just ask the Google Assistent.

**Comment by duncan3dc** [comment]
Hi @vespino, that's right I use this library for something very similar to that myself.

Sonos do provide some of the functionality you're describing using their "alarms" feature, so it may be worth looking at that before digging into this library.

But this library can certainly handling playing, stopping, grouping, etc
