### ISSUE TITLE
Call to a member function getTags()

### ISSUE THREAD

**Issue by vespino** [duncan3dc/sonos#113]
I have just bought 3 Sonos One Gen 2 speakers and installed 2 of them. I have quickly installed this program to see if it works with the following code:

```
require_once "../vendor/autoload.php";
use duncan3dc\Sonos\Network;
$sonos = new Network;
$speakers = $sonos->getSpeakers();
print_r($speakers);
```

All it currenty does is output the following error: Fatal error: Uncaught Error: Call to a member function getTags() on boolean in /path/to/script/vendor/duncan3dc/sonos/src/Network.php:279

I trying to run this on my Synology NAS which is running PHP 7.0.33. What can I do to troubleshoot and get things running?

**Comment by duncan3dc** [comment]
Hi @vespino 

Please [enable logging](http://duncan3dc.github.io/sonos/setup/logging/) and run your code again, then paste the output here or in a gist, that should help figure out what's going on

**Comment by vespino** [comment]
[2020-11-26 21:58:03] sonos.INFO: creating speaker instances [] []
[2020-11-26 21:58:03] sonos.INFO: getting device info from cache [] []
[2020-11-26 21:58:03] sonos.NOTICE: Getting topology info from: http://x.x.x.x:1400/status/topology [] []

Fatal error: Uncaught Error: Call to a member function getTags() on boolean in /path/to/file/vendor/duncan3dc/sonos/src/Network.php:279
Stack trace:
#0 /path/to/file/sonos/test.php(13): duncan3dc\Sonos\Network->getSpeakers()
#1 {main}
  thrown in /path/to/file/vendor/duncan3dc/sonos/src/Network.php on line 279

I can't open this page in a browser: http://x.x.x.x:1400/status/topology

**Comment by duncan3dc** [comment]
That line number looks suspicious, doesn't appear to line up with the current version of this library.
Did you install via composer? If so what version is installed? (you can use something like `composer show | grep sonos` to check)

**Comment by vespino** [comment]
duncan3dc/sonos                  1.9.11    Control Sonos speakers using a simple API

**Comment by duncan3dc** [comment]
Ah that's quite an old version, almost exactly 3 years old to the day!

I can only spare enough time to support the latest version, which is 2.1.1 (https://github.com/duncan3dc/sonos/tags) at the moment.

Please upgrade to that and try again, if you still experience issues on the latest version I'd be happy to investigate further

**Comment by vespino** [comment]
Can you tell me how to upgrade? Download from github and overwrite? Any guess to why composer did not install the latest version?

**Comment by duncan3dc** [comment]
You can just use composer to upgrade, I would guess perhaps your PHP version is quite old, so composer is given you an old version of this library that is compatible with the old version of PHP. Do you know what version of PHP you are using?

**Comment by vespino** [comment]
I'm using 7.0.33.

**Comment by vespino** [comment]
Yeah buddy! Installed PHP72 and things are rolling!
