### ISSUE TITLE
Stop?

### ISSUE THREAD

**Issue by vespino** [duncan3dc/sonos#114]
Got it running thanks to your tip on upgrading PHP. I was able to join several speakers and have them play without any lag using TuneIn. Great documentation btw!

One thing I wasn't able to find was the simple "stop" command. Is there only "Pause()"?

**Comment by duncan3dc** [comment]
Fantastic :tada: 

The Sonos speakers only provide pause when playing tracks from the queue, I think the App does show a "stop" icon when you're listening to a stream or line-in, but the `pause()` method should do the same thing
