### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by vespino** [duncan3dc/sonos#115]
I'm trying to implement caching: https://duncan3dc.github.io/sonos/setup/cache/

I have installed this [script](https://packagist.org/packages/symfony/cache) but on calling the following I'm getting an error:

`$collection = new Discovery();`

`Fatal error: Uncaught Error: Class 'Discovery' not found in /path/to/my/script.php:60`

I'm not used to using composer all that much, so what do I have to add to the following:

```
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Interfaces\Services;
use duncan3dc\Sonos\Tracks\Stream;
```

I have tried:

```
use duncan3dc\Sonos\Devices;
use duncan3dc\Sonos\Interfaces\Devices\CollectionInterface;
```

I have also added:

`use Psr\SimpleCache\CacheInterface;`

**Comment by duncan3dc** [comment]
Hi @vespino looks like you'll want `use duncan3dc\Sonos\Devices\Discovery` in there to import the `Discovery` class.
I'll leave this issue open until I fix the docs to include this

**Comment by vespino** [comment]
Ok, that solves the Discovery class error, now I'm getting this error:

`Fatal error: Uncaught Error: Class 'Symfony\Component\Cache\Simple\FilesystemCache'`

What else should I add to the mix?

```
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Interfaces\Services;
use duncan3dc\Sonos\Tracks\Stream;
use duncan3dc\Sonos\Devices\Discovery;
use Psr\SimpleCache\CacheInterface;
```

Again sorry, I rather using the oldskool include.

**Comment by vespino** [comment]
@duncan3dc any thoughts on this?

**Comment by duncan3dc** [comment]
It looks like Symfony removed the simple filesystem cache in 5.x:
https://github.com/symfony/cache/blob/5.x/CHANGELOG.md
Try `composer require symfony/cache:^4.0` instead

**Comment by vespino** [comment]
Tried this and it didn't at all make things faster. I also tried saving the collection object for later use, this also didn't speed things up more that a second or two, so I'll stick with simply scanning every time. Thanks!

**Comment by mikenadeau** [comment]
Sorry to re-open this old thread, but I'm trying to implement caching in my project, and this is the only thread I found related to what I'm trying to do.

I'm using Symfony 4.x to have access to Simple\FilesystemCache.

My question is: IP addresses are cached, but when running getSpeakers, it's still taking many seconds to execute. Is there a way to add all speakers info into the cache and speed up considerably getSpeakers?

`require_once __DIR__ . "/vendor/autoload.php";

use duncan3dc\Sonos;
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Devices\Discovery;
use duncan3dc\Sonos\Devices\CachedCollection;
use Symfony\Component\Cache\Simple\FilesystemCache;

$collection = new Discovery;
$cache = new FilesystemCache;
$collection = new CachedCollection($collection, $cache);
$sonos = new Network($collection);

// How could we cache this?
$speakers = $sonos->getSpeakers(); `

Thanks!
