### ISSUE TITLE
function seek with option track number in queue 

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#12]
I am able to move forward on a track of number in the queue. I dont want this feature in your api

**Comment by duncan3dc** [comment]
Please can you explain more? Maybe with an example?

**Comment by 889laurent** [comment]
thanks for your answer.
i want to play a message . i used "$queue->addTrack("x-file-cifs://" .$directory ."/TTS-63af97a14a6f2f5596a868b521a382d0.mp3" ); "
the message is in the last position af the queue
i want to play this.

if i addtrack in 1 position when i play that play message and other tracks after in queue

i added in your code this function
public function SeekNumber($position)
	     {
            return $this->soap("AVTransport", "Seek" ,   [
            "Unit" =>  'TRACK_NR' , "Target" => $position,
        ]);
  	}	
	public function SeekTime($time)
	{
		          return $this->soap("AVTransport", "Seek" ,   [
            "Unit" =>  'REL_TIME' , "Target" => $time,
        ]);
 
	}
i tried help with djmomo/sonos code

**Comment by duncan3dc** [comment]
I understand, I'll take a look at adding a seek track/time function soon

**Comment by duncan3dc** [comment]
I've added this in ac55595270d727e67a8d7cdb35d7e3fb5c60e4ee now, I'll be tagging a new release a little bit later with some new documentation
