### ISSUE TITLE
Legacy league/flysystem could lead to vulnerability

### ISSUE THREAD

**Issue by dutchie027** [duncan3dc/sonos#121]
[The default composer.json](https://github.com/duncan3dc/sonos/blob/main/composer.json) requires league/flysystem 1.0 or greater. Anything less than 1.1.4 has [a security issue detected](https://github.com/advisories/GHSA-9f46-5r25-5wfm). I know there is an [upgrade branch](https://github.com/duncan3dc/sonos/tree/upgrade) which I'm guessing is to go along with the other PHP 8.0 changes, but I was wondering how this was coming along or if there was a need for PRs to get this lib to 8.0 as well (including updating libs for security, etc).

**Comment by duncan3dc** [comment]
This should be resolved in [2.2.0](https://github.com/duncan3dc/sonos/releases/tag/2.2.0) now
