### ISSUE TITLE
TV playback function on the playbar

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#13]
The TV playback function not works with play() command. On sonos controler there a special function that do it

**Comment by 889laurent** [comment]
the uri command return nothing when the spdif input is on

**Comment by 889laurent** [comment]
i tried to addtrack wirh this uri (x-sonos-htastream:RINCON_B8E9377DB02301400:spdif) and i have error message
PHP Fatal error:  Uncaught exception 'duncan3dc\Sonos\Exceptions\SoapException' with message 'UPnPError: 804' in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php:120
Stack trace:
#0 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(93): duncan3dc\Sonos\Device->soap('AVTransport', 'AddURIToQueue', Array)
#1 /var/www/duncan/vendor/duncan3dc/sonos/src/Queue.php(62): duncan3dc\Sonos\Speaker->soap('AVTransport', 'AddURIToQueue', Array)
#2 /var/www/duncan/vendor/duncan3dc/sonos/src/Queue.php(199): duncan3dc\Sonos\Queue->soap('AVTransport', 'AddURIToQueue', Array)
#3 /var/www/duncan/vendor/duncan3dc/sonos/src/Queue.php(159): duncan3dc\Sonos\Queue->addTracks(Array, NULL)
#4 /var/www/duncan/a.php(22): duncan3dc\Sonos\Queue->addTrack('x-sonos-htastre...')
#5 {main}
  thrown in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php on line 120

**Comment by duncan3dc** [comment]
This is being tracked under issue #7
