### ISSUE TITLE
Add command for save state of every speker and pause

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#17]
in my house, i want to play tts alert message on all speaker (or special speaker). 
i create a controller with all speker i want to add, before i want to save state and pause(speaker are playing) speaker.
play tts with special volume
after play tts, restore state before create group and play speaker with state pause.

if you add an function with everything i talk before, its a good idea

**Comment by duncan3dc** [comment]
Once the TTS functionality and Export/Restore State is done I will consider whether this makes sense to put in the library, or be handled in user code by developers that want this specific functionaity

**Comment by 889laurent** [comment]
thanks for your reply. This function will be interesting for inexperienced Developer. Maybe to give the example only

**Comment by duncan3dc** [comment]
Grouping and ungrouping speakers can be quite fragile and sometimes take a couple of seconds to do, so I'm hesitate to add any code that depends on those actions running smoothly.

However, when version 1.2 is released you will be able to do this:
```php
$directory = new Directory("/var/shares/sonos", "HOSTNAME/sonos", "tts");
$track = new TextToSpeech("Urgent Announcement", $directory);

foreach ($sonos->getControllers() as $controller) {
        $controller->interupt($track);
}
```

So they won't necessarily be in sync, but they will all play the announcement and then continue what they were doing before.

**Comment by 889laurent** [comment]
y have an error message with code (PHP Fatal error:  Call to undefined method duncan3dc\Sonos\Controller::interupt() in /var/www/duncan2/testtts.php on line 20)
line 20 :  $controller->interupt($track);
thanks for your help

**Comment by duncan3dc** [comment]
`interrupt` should have 2 `r`'s in it

**Comment by 889laurent** [comment]
ok

**Comment by 889laurent** [comment]
sorry

**Comment by 889laurent** [comment]
i test this code
$sonos->getControllerByRoom("Salon TV")->interrupt($track);
$sonos->getControllerByRoom("Piscine")->interrupt($track);
$sonos->getControllerByRoom("Pergola")->interrupt($track);
and there are error upnp 711
when i erase 1 line or i test with 1 line its works fine ? the error is when i have >= 2 lines
