### ISSUE TITLE
TuneIn support?

### ISSUE THREAD

**Issue by rjgdesign** [duncan3dc/sonos#19]
This is perfect, or nearly perfect!

Is there TuneIn support? Would love.

**Comment by duncan3dc** [comment]
I'll look into this

**Comment by rjgdesign** [comment]
Super! Be much appreciated, really would. :)

**Comment by rjgdesign** [comment]
Also, is there anyway I could upload this to a web server, and use it from there? If so, how would I go about that? Cheers!

**Comment by duncan3dc** [comment]
The web server would need to be on the same network as your Sonos devices, you can run a webserver from php anywhere though: http://php.net/manual/en/features.commandline.webserver.php

**Comment by rjgdesign** [comment]
Ah okay. So a device always has to be on, to run it.

**Comment by duncan3dc** [comment]
Sorry for the delay, this is now available in [version 1.3.1](http://duncan3dc.github.io/sonos/services/radio/)

**Comment by duncan3dc** [comment]
As this is very basic support I'm going to re-open this issue until we can search for stations/shows by name, and other essential features

**Comment by zoic21** [comment]
I juste test this fonctionality and it's ok (of course search by name can be usefull). But I have one question when I play a radio hox can I return to playlist ? I see my playlist on sonos interface but I don't know how can I switch from radio to playlist.

**Comment by duncan3dc** [comment]
@zoic21 Do you mean the queue? The [docs](http://duncan3dc.github.io/sonos/controllers/queue/) have info on how to switch between using a queue or using a stream. If the docs are missing something please let me know and I'll get it added

**Comment by zoic21** [comment]
Thank I missed this doc it's perfectly work

**Comment by duncan3dc** [comment]
`Radio::getFavouriteStation($name)` and `Radio::getFavouriteShow($name)` are [now available](http://duncan3dc.github.io/sonos/services/radio/)
