### ISSUE TITLE
 UPnPError: 701 and  UPnPError: 711

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#21]
Hi,

I have this errorabout twice a day. What does it mean ?

Thank in advance

**Comment by duncan3dc** [comment]
701 is `'Transition not available'` which sounds like trying to play music when it's playing, or maybe trying to play an empty queue.
711 is `'Illegal Seek Target'` which sounds like trying to seek beyond the end of a song, or to the next track when you're already at the end of the queue.

There is a comprehensive list of UPnP error codes at the link below:
https://msdn.microsoft.com/en-GB/library/ms899567.aspx
