### ISSUE TITLE
Title of radio

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#24]
Hi,

I just test radio support, but I can't find how can I get the radio name ?

Thank in advance

**Comment by duncan3dc** [comment]
Sorry, looks like I messed up the release and missed some code, I'll get a patch release together shortly...

**Comment by duncan3dc** [comment]
This is in version 1.3.3 now

```php
foreach ($sonos->getRadioStations() as $station) {
    echo $station->getTitle() . "\n";
}
```

Keep an eye on issue #19 for further radio features

**Comment by zoic21** [comment]
Thank it's work
