### ISSUE TITLE
Add Track from Spotify: bad title, no preview image 

### ISSUE THREAD

**Issue by breath20** [duncan3dc/sonos#25]
So i have been playing around with adding a track via streaming or a queue that is a spotify track. When i do it plays fine, but on the sonos app it does not have the correct title or album art (its blank)

I tried pushing that information into the track but it didn't seem to take so i'm not sure whats going on. 

$track = new \duncan3dc\Sonos\Tracks\Track("x-sonos-spotify:6ZOBP3NvffbU4SZcrnt1k6?sid=12&flags=32&sn=1");
$queue->addTrack($track);
$controller->selectTrack(0);
$controller->play();

Is this not supported, am i doing something wrong ? I'm guessing i'm doing something wrong, any help would be greatly appreciated.

**Comment by duncan3dc** [comment]
You need to produce the relevant metadata to get it to display the track information. Unfortunately it seems to require some [hashed value](https://github.com/duncan3dc/sonos/blob/c0068112913383b389ae9aa9f5713e5fbc539e3d/src/Services/AbstractSpotify.php#L55) that I've not been able to figure out yet.

I didn't know it could be done as a stream like in your example though, so might investigate that approach as it's better than nothing. Currently the random hash fails about 50% of the time, which isn't good enough to release.

**Comment by dccampbell** [comment]
This might be relevant to this issue, I just noticed that I never get album art when streaming Spotify, or more accurately I get a malformed image url. 

It looks like in this case the albumArtURI is a complete url as opposed to a relative path, so the bit at the bottom of `Track.php` where the URI is appended to the controller IP throws it off (resulting in albumArt returning `http://sonos-ip:1400http://spotify-img-url`).

I think it just needs a check around the sprintf call to make sure $art isn't a complete url first.

**Comment by duncan3dc** [comment]
Thanks @dccampbell, 1.6.0 will have better Spotify support, and I'll make sure album art is handled as part of that

**Comment by duncan3dc** [comment]
Version `1.6.0` just released has support for adding [Spotify tracks](http://duncan3dc.github.io/sonos/services/spotify/) and should fix the album art issue
