### ISSUE TITLE
error with name of tracks when use interrupt with deezer list

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#26]
Good morning, i opened this issues because i install the last version and when i use interrupt command and i have a playlist with deezer tracks the name in the list are with bad format (x-sonos-http:tr:1213131313.mp3....)
![capture d ecran 2015-06-14 a 22 06 54](https://cloud.githubusercontent.com/assets/8254672/8181814/7c30f5d4-1429-11e5-8c09-0949d4351309.png)

**Comment by 889laurent** [comment]
sorry for my demand . Have you identified the bug or its my config ?

**Comment by duncan3dc** [comment]
Sorry for the lack of feedback, it looks like a bug but I've not found time to investigate yet

**Comment by 889laurent** [comment]
thanks for your feedback.

**Comment by 889laurent** [comment]
good morning, have you resolved the problem ?
thanks

**Comment by duncan3dc** [comment]
No, as I don't have a Deezer subscription this is going to be very difficult to investigate and provide a solution for

**Comment by 889laurent** [comment]
Thanks for your answer. if you want i,m give you may id et pass of deezer by mail

**Comment by duncan3dc** [comment]
That would be great, if you could send it to `git` `AT` `duncanc.co.uk` I'll see if I can sort something out this week for you

**Comment by duncan3dc** [comment]
Thanks for that @889laurent, this should be fixed in version `1.6.0` now.
And there's also a [Deezer](http://duncan3dc.github.io/sonos/services/deezer/) class that allows you to add tracks
