### ISSUE TITLE
long time after interrupt command with long playlist

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#27]
when i use interrupt command with a long playlist (200 Tracks) , there is a long time to replay interrupt track. i think it's better to add interrupt-track a the end of list and remove after. 
for test i tried this:
- save state (volume, number of playing track , ...)
- shuffle off 
- add track
- play
- remove track
-restore state

**Comment by duncan3dc** [comment]
That's an interesting idea, I'll have to play around with it a bit first, feel free to submit a pull request though

**Comment by duncan3dc** [comment]
Version 1.5 improves the performance when adding multiple tracks to a queue (this was the cause of the speed issue with `interrupt()`)

I ran some tests before and after, with 274 tracks in the queue:
```
Version 1.4.2 - 55 seconds
Version 1.5.0 -  3 seconds
```
