### ISSUE TITLE
ZP80 Support

### ISSUE THREAD

**Issue by dccampbell** [duncan3dc/sonos#29]
`isSpeaker()` in `Device.php` defines speakers by their model number, but is missing the original ZonePlayer, the ZP80. This prevents getting data from the device nor any groups it's a part of. I believe it should work the same as a ZP90, and just needs to be added to the static list.

**Comment by duncan3dc** [comment]
Can you edit your version to add in `ZP80` and `ZP90` and then check if it works? I'd rather have confirmation that they work correctly before adding in code that says they do

**Comment by dccampbell** [comment]
Added the ZP80 and so far I'm not having any issues. I'm getting all the expected data now just like the other models. :+1:

**Comment by duncan3dc** [comment]
This will be available in version `1.5.1` shortly
