### ISSUE TITLE
Getting a UPnPError: 800 when trying to use the Spotify Track

### ISSUE THREAD

**Issue by breath20** [duncan3dc/sonos#31]
Not sure whats going on, but still am unable to make the Spotify Track work (was so excited :p ) 

$sonos = new \duncan3dc\Sonos\Network;
$controller = $sonos->getControllerByRoom("Bathroom");
if (!$controller->isUsingQueue()) {
    		$controller->useQueue();
    	}
$queue = $controller->getQueue();
$queue->clear();
$track = new \duncan3dc\Sonos\Tracks\Spotify("1Jb9SZDqMN5Zyxiwy6eiEA");
$queue->addTrack($track);
$controller->play();

The addTrack Method is what is throwing the SoapException. 

If i replace the $track line with 
$track = new \duncan3dc\Sonos\Tracks\Track("x-sonos-spotify:spotify:track:1Jb9SZDqMN5Zyxiwy6eiEA?sid=12&flags=32&sn=1");

The track will play (missing album art and title, but this is the only way i have been able to make it work so far) 

Thoughts, suggestions ?

**Comment by duncan3dc** [comment]
That code works for me, I wonder if we need a different [token](https://github.com/duncan3dc/sonos/blob/ddeec250933bb59fa85d5ce31c7890e5a459ba3d/src/Tracks/Spotify.php#L47) per account/system.

I think there's some kind of session token lookup in Sonos, I'll see if I can find something on that

**Comment by breath20** [comment]
Do some quick googling it looks like "SA_RINCON2311_X_#Svc2311-0-Token" refrences a EU service for spotify, i'm not running off a EU service for spotify im in the US. Could be the problem

**Comment by duncan3dc** [comment]
That'll be it, at least that's easier to handle than a per user one. I'll see if I can find the token for each Spotify service and add a configuation option for it

**Comment by breath20** [comment]
So looking at my sonos info, it uses "SA_RINCON3079_X_#Svc3079-0-Token" if i replace it with that works like a charm.

**Comment by duncan3dc** [comment]
This is available in `1.7.0` now:
```php
Spotify::$region = Spotify::REGION_US;
```
[http://duncan3dc.github.io/sonos/services/spotify/](http://duncan3dc.github.io/sonos/services/spotify/)
