### ISSUE TITLE
Does this api support Grouping Speakers together to play the same Queue

### ISSUE THREAD

**Issue by breath20** [duncan3dc/sonos#32]
Looking at the code i'm not sure it does, but if it can great. If not i will be branching and making it work :)

**Comment by duncan3dc** [comment]
It sure does:
```php
$controller = $sonos->getControllerByRoom("Living Room");
$speaker = $sonos->getControllerByRoom("Spare Room");

$controller->addSpeaker($speaker);
```
Relevant section of the [docs](http://duncan3dc.github.io/sonos/controllers/speakers/)
