### ISSUE TITLE
TrackFactory missing on Playlist

### ISSUE THREAD

**Issue by remo-moddit** [duncan3dc/sonos#33]
When using Playlist.getTracks or Playlist.addTracks, an error is thrown about Playlist.trackFactory not being an object. Trackfactory is initialized in the constructor of base class Queue, but not in the constructor of Playlist.
Propably this line should be prepended to Playlist->__construct() : 
```PHP
        parent::__construct($controller);
```

**Comment by duncan3dc** [comment]
Sorry about that, that should be fixed in release `1.6.1`
