### ISSUE TITLE
TTS : use SMB directly without local mount

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#34]
Hi,
I see commit with flysystem I wonder if it's possible to directly push mp3 file to smb share (with flysystem-smb) without mount it to local filesystem ?

Thank in advance

**Comment by duncan3dc** [comment]
Sure, just pass your flysystem instance to the `Directory` class (instead of the local path string):

```php
use duncan3dc\Sonos\Directory;
use Icewind\SMB\Server;
use League\Flysystem\Filesystem;
use RobGridley\Flysystem\Smb\SmbAdapter;

$server = new Server("host", "username", "password");
$share = $server->getShare("sharename");

$adapter = new SmbAdapter($share);
$filesystem = new Filesystem($adapter);

$directory = new Directory($filesystem, "host/sharename", "tts");
```

http://duncan3dc.github.io/sonos/fun/announcements/

**Comment by zoic21** [comment]
Thanks a lot it's perfectly work
