### ISSUE TITLE
Adding a track to a playlist

### ISSUE THREAD

**Issue by Paco777** [duncan3dc/sonos#37]
Hi,
Thanks a lot for this php library. It gives a lot of possibilities !

Is the functionality to add a track to a playlist still working ?
Everything I've been trying so far has no effect.

I can get an existing playlist, and get the existing tracks in it. I can also clear it (if not empty), however adding a new track to it gives no error but does not seem to work.

Am I missing something ?

**Comment by duncan3dc** [comment]
It looks like something broke in version `1.5.0`, you can use `1.4.2` for now until I can get it fixed

**Comment by Paco777** [comment]
Thank you !
With 1.4.2 (and a few things from 1.5.0), I have everything working as expected.

**Comment by duncan3dc** [comment]
This is fixed in `1.7.1` thanks for your patience

**Comment by Paco777** [comment]
Thank you :)
