### ISSUE TITLE
Create method to manually add speaker

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#38]
Hi,
It's possible to create method tp manually add speaker ? I explain if I run sonos php file into a docker the discovery failed due to network (docker create an internal network so SSDP failed). But if I known IP of sonos I think I can control them and get information of it.

Thank in advance.

**Comment by duncan3dc** [comment]
Sure, you should be able to do the following:
```php
use duncan3dc\Sonos\Speaker;

$speaker = new Speaker("192.168.0.22");
```

Does that work?

**Comment by zoic21** [comment]
Yes it's work but I need method on networks to reinject speakers like that

````
public function setSpeakers($speakers) {
		$this->speakers = $speakers;
		return $this;
}
````

With it I can add speaker into network and all it's work. It's possible to add this function ?

**Comment by duncan3dc** [comment]
Why do you need that? The `Network` class is only really used to find devices, if you already have the devices then what benefit does injecting them into your network instance give you?

**Comment by zoic21** [comment]
Because after that I need Controller, I known I can make it with speaker but I think use standard fonction like getControllerByIp is better. And I wonder if I don't reinject speaker into network function like getPlaylists will work ?

**Comment by duncan3dc** [comment]
Ok I see, it should be possible to do everything with a network instance, but I guess it's a little awkward, let me give it some thought

**Comment by zoic21** [comment]
Thank in advance (for all your work)

**Comment by duncan3dc** [comment]
I've done [some work](https://github.com/duncan3dc/sonos/commit/08f7e7872400e9381fb1d0940cd61c159b78714c) on this, but it will form part of the next major release (2.0) with some backwards incompatible changes. But when it's ready you'll be able to do something like:
```php
$devices = new DeviceCollection;
$devices->addIp("192.168.0.22");
$devices->addIp("192.168.0.37");

$sonos = new Network($devices);
```

**Comment by duncan3dc** [comment]
Hi @zoic21, version 2.0 is finally nearing release now, this will enable you to manage the devices on the network yourself like so:
```php
$factory = new \duncan3dc\Sonos\Devices\Factory;
$devices = new \duncan3dc\Sonos\Devices\Collection($factory);

$devices->addIp("192.168.0.22");
$devices->addIp("192.168.0.37");

$sonos = new \duncan3dc\Sonos\Network($devices);
```
Here's [the documentation](http://duncan3dc.github.io/sonos/v2/) I've got so far, please take a look and let me know if you see any issues

**Comment by zoic21** [comment]
Thank, I just pass to version 2.0, all seem ok, I just had one issue : 
- in Discovery.php, in method getMulticastAddress, is missing $this-> , after fix that all is ok

**Comment by duncan3dc** [comment]
Thanks Loic, that's great. I'll let you know when 2.0 is ready for release

**Comment by duncan3dc** [comment]
Hi @zoic21, I'm so sorry for the delay, but [2.0.0](https://github.com/duncan3dc/sonos/releases/tag/2.0.0) was finally just released.

I'll be updating the docs soon, but there's a page that outlines some of the major differences [here](http://duncan3dc.github.io/sonos/v2/) and of course the [CHANGELOG](https://github.com/duncan3dc/sonos/blob/master/CHANGELOG.md)
