### ISSUE TITLE
Fatal error: Uncaught exception 'RuntimeException'

### ISSUE THREAD

**Issue by christwigg1974** [duncan3dc/sonos#39]
Firstly, thanks for writing such an amazing API.

I'm receiving the following error 
Fatal error: Uncaught exception 'RuntimeException' with message 'No devices found on the current network' in C:\xampp-composer\htdocs\soco\vendor\duncan3dc\sonos\src\Network.php:215 Stack trace: #0 C:\xampp-composer\htdocs\soco\vendor\duncan3dc\sonos\src\Network.php(377): duncan3dc\Sonos\Network->getSpeakers() #1 C:\xampp-composer\htdocs\soco\sonos.php(6): duncan3dc\Sonos\Network->getControllerByIp('192.168.0.125') #2 {main} thrown in C:\xampp-composer\htdocs\soco\vendor\duncan3dc\sonos\src\Network.php on line 215

My Code:
<?php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;
$sonos = new Network;
$controller = $sonos->getControllerByIp("192.168.0.125");
?> 

I've tried using 
$speakers = $sonos->getSpeakersByRoom("Speaker Name");
$controller = $sonos->getControllerByIp("IP Address");

but everything produces the error...... please help

Many Thanks

**Comment by duncan3dc** [comment]
Hi Chris, I presume your Sonos devices are on the same network as the server you are running the PHP code on?

What Sonos devices do you have?

**Comment by christwigg1974** [comment]
Hi Craig 

I really appreciate you helping me.

Yes all on the same network 192.168.0.0/24

I have a sonos 
Play 3 192.168.0.101
Play 5 192.168.0.125

**Comment by duncan3dc** [comment]
Ok, could you try turning logging on and posting the result in a gist?
You can do this using `monolog` like so:
```sh
composer require monolog/monolog
```
```php
$logger = new \Monolog\Logger("sonos");
$logger->pushHandler(new \Monolog\Handler\StreamHandler("/tmp/sonos.log", \Monolog\Logger::DEBUG));
$sonos->setLogger($logger);
```

**Comment by christwigg1974** [comment]
I have installed monlog and added code but no log files are being produced.

<?php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;
$sonos = new Network;
$logger = new \Monolog\Logger("sonos");
$handler = new \Monolog\Handler\StreamHandler("/tmp/sonos.log", \Monolog\Logger::DEBUG);
$logger->pushHandler($handler);
$sonos->setLogger($logger);
?>

**Comment by christwigg1974** [comment]
[2015-11-04 00:00:49] sonos.INFO: creating speaker instances [] []
[2015-11-04 00:00:49] sonos.INFO: discovering devices... [] []
[2015-11-04 00:00:49] sonos.DEBUG: M-SEARCH * HTTP/1.1 HOST: 239.255.255.250:reservedSSDPport MAN: ssdp:discover MX: 1 ST: urn:schemas-upnp-org:device:ZonePlayer:1  [] []
[2015-11-04 00:00:50] sonos.DEBUG:  [] []

**Comment by christwigg1974** [comment]
I've managed to sort the problem by using an Ubuntu server installation.

Windows 8.1 clearly has a problem, maybe with sockets.

Just need to figure out how to use the code now. 

Thanks for looking into it.

**Comment by duncan3dc** [comment]
Ahh, maybe a similar issue to #4? Perhaps a windows firewall configuration issue?

Glad you got it working one way or the other, hope you find a solution to running on Windows
