### ISSUE TITLE
No devices found on OS X when running as normal user

### ISSUE THREAD

**Issue by burriko** [duncan3dc/sonos#4]
As mentioned on reddit, I get an exception saying "No devices found on the current network" when I call getControllers().

I've since tried the same code in a Linux VM, and it found the devices fine.  I then tried running the code again on OS X, but this time running as root, which also worked fine.  So it would seem to be a networking permissions issue from PHP when running as a normal user on OS X.

This may not be something that you can fix, but I thought I'd better still document it here in case anyone else runs into the problem.

**Comment by burriko** [comment]
More digging, and the actual problem was that the first time I ran the code the Sonos systems couldn't be discovered (don't know why) and this result was cached. So all subsequent calls were using the cached result of 'No devices found'.  Clearing the cache has fixed the issue.

I suppose the network discovery should only be cached if it actually finds devices.  Still, it seems to be cached forever at the moment (unless I'm missing something) which probably isn't ideal. (new devices could be added, devices could change network location, etc.)

**Comment by duncan3dc** [comment]
Thanks for the report @burriko, I suspected it might have been a miss-cache.
Do you have any error reporting levels hidden? Maybe a warning went unnoticed.

Only caching when we find some devices makes sense to me, I'll make that change which should avoid this issue in the future

**Comment by burriko** [comment]
Thinking back I do now remember the OS X firewall dialog popping up the first time I tried it, and by the time I'd clicked to 'Accept' the connection the script had already failed. So that'll be what caused the initial error, which was still reported as the Exception for no devices found. I didn't think much of it at the time as all subsequent runs gave the same error despite the firewall being disabled. Which of course I now know was because the initial failed response was cached.

**Comment by duncan3dc** [comment]
That explains it then. As of [1.0.2](https://github.com/duncan3dc/sonos/releases/tag/1.0.2) failed discoveries are no longer cached. Thanks for your help.
