### ISSUE TITLE
Group players, save state, make announcement/TTS, resume.

### ISSUE THREAD

**Issue by christwigg1974** [duncan3dc/sonos#41]
Hi, It's not an issue.... Its me, i need help creating code. I'm not a coder, far from it.
I'm doing some home automation and require a doorbell to be played through sonos. Group players, save state, make announcement/TTS, resume state.

I have created the code below which does work for one controller/speaker only, Is there a better way to achieve the desired effect. Ie without creating a sleep, i don't want to change the code every time i choose a different doorbell mp3 and using all speakers i own now or will add to in the future.

I have also tried the announcements which reads like it would work perfectly but fails on the $bedroom->interrupt($track); Is it possible to play a saved mp3 as the $track ?

Are there any examples available for TTS ? I do not understand what to "use"

<?php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;
$sonos = new Network;
$controller = $sonos->getControllerByRoom("Living Room");
$state = $controller->exportState(true);
$queue = $controller->getQueue();
$queue->clear();
$queue->addTrack("x-file-cifs://192.168.0.7/Music/Sonos/doorbell-1.mp3");
$controller->useQueue(); // if the radio is streaming the queue is not active.
$controller->setVolume(60);
$controller->play();
sleep(4); //pause for the length of doorbell mp3 otherwise restore state too early.
$controller->restoreState($state);
?>

Really enjoying the PHP Library and appreciate all the hard work that has gone into it!!

Thanks

**Comment by duncan3dc** [comment]
As you mentioned, the `interrupt()` method does exactly what you need, what error are you seeing when you try it?
