### ISSUE TITLE
get/setVolume vs groupVolume

### ISSUE THREAD

**Issue by csahut** [duncan3dc/sonos#42]
Hi,

 Would it be possible to have a differentiation between the get/setVolume for a speaker and for a group? When players are grouped, setVolume for example set the same volume for all speakers. I would like to adjust each volume individually while playing the same song in a group (I want to create scenarios with different volume sets depending on where I am in the flat).

This feature is available in this node library for example: https://github.com/jishi/node-sonos-http-api

**Comment by duncan3dc** [comment]
You can set the volume for a group using a [Controller](http://duncan3dc.github.io/sonos/controllers/volume/).
You can set the volume for a speaker using a [Speaker](http://duncan3dc.github.io/sonos/usage/speakers/)

Is that what you need?

**Comment by csahut** [comment]
Yes! Sorry for the noise. Actually I use Sonos plugin for Jeedom (which uses your library) and this does not make the differentiation. I quickly looked at the code and didn't find an groupVolume function, I thought it was just not implemented in your library. I'm going to check at the plugin level then.

Thanks for your help and for your work!

**Comment by duncan3dc** [comment]
No problem, glad you're finding the library useful
