### ISSUE TITLE
Add google music service

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#48]
Hi,

I would like to play a "theme playlist" (or radio like google call it), I think for now it's not possible, how can I provide "tools" to add this ?

Thank in advance.

**Comment by duncan3dc** [comment]
Hi, it should be possible, we just need to support the `x-rincon-cpcontainer` syntax. I had a go when I was working on Spotify tracks (to support albums) but I ran into some issues. I'll take another look when I get some time

**Comment by duncan3dc** [comment]
Hi @zoic21, I've had some success with this, I managed to get some of my "Instant Mixes" to stream like so:

```php
$stream = new GoogleInstantMix("B4ou4r6IfwqPy1CcTt4XPSS3wb8rdgHCtTWwCQLH1o2EtbZEXSzLc5MmU44ByL1u");
$controller->useStream($stream);
```
You can check this out by trying `composer require duncan3dc/sonos:dev-google-instant-mixes`

Let me know if this is in the right direction, then I'll see if I can find a way to retrieve a list of available mixes for you

**Comment by duncan3dc** [comment]
It looks like Google Music was shutdown in 2020 so this functionality is no longer possible
