### ISSUE TITLE
Problem with groups

### ISSUE THREAD

**Issue by hyperbolic2346** [duncan3dc/sonos#49]
I'm in the alpha for Sonos, so maybe something has changed, but I'm not seeing consistent results from the library. Here is an example program:

```<?php

require_once __DIR__ . "/vendor/autoload.php";

$sonos = new \duncan3dc\Sonos\Network;

$speaker = $sonos->getSpeakerByRoom("Nursery");
print "speaker in room $speaker->room is $speaker->name\n";
print "speaker group is " . $speaker->getGroup() . "\n";
print "speaker is " . ($speaker->isCoordinator() ? "" : "not ") . "coordinator\n";

$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
  print "Controller $controller->room has group " . $controller->getGroup() . "\n";
  $speakers = $controller->getSpeakers();
  foreach ($speakers as $speaker) {
    print "  - Speaker $speaker->name\n";
  }
}
```

And here is the output:

```
speaker in room Nursery is 10.0.1.175 - Sonos PLAY:5
speaker group is RINCON_000E585C29F001400:126
speaker is coordinator
Controller Nursery has group RINCON_000E585C29F001400:96
Controller Living Room has group RINCON_B8E93771A1A701400:320
  - Speaker 10.0.1.115 - Sonos PLAYBAR
Controller Guest Room has group RINCON_000E58A5036C01400:43
  - Speaker 10.0.1.155 - Sonos CONNECT
Controller Bathroom has group RINCON_000E5855F8BE01400:85
  - Speaker 10.0.1.126 - Sonos PLAY:5
```

Notice the Nursery speaker has a group that doesn't match the controller's group. Is the :126 part new from the alpha?

**Comment by duncan3dc** [comment]
Is the only issue the group ID? Is it still recognising the correct speakers in each group?

Do you have any stereo pairs?

Could you get some [log data](https://duncan3dc.github.io/sonos/logging/) so I can check if anything has changed in the alpha.

Make sure to [clear the cache](https://duncan3dc.github.io/sonos/setup/#cache) or use something like ArrayCache

**Comment by duncan3dc** [comment]
@hyperbolic2346 Please feel free to re-open this issue if you can provide the information above
