### ISSUE TITLE
exemple

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#5]
please send me a complete exemple of php for play on speakers name "salon". I tried your application but there this message
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'couldn't connect to host' in /var/www/duncan/vendor/duncan3dc/helpers/src/Helper.php:664
Stack trace:
#0 /var/www/duncan/vendor/duncan3dc/domparser/src/Parser.php(29): duncan3dc\Helpers\Helper::curl('http://192.168....')
#1 /var/www/duncan/vendor/duncan3dc/domparser/src/XmlParser.php(29): duncan3dc\DomParser\XmlParser->getData('http://192.168....')
#2 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(80): duncan3dc\DomParser\XmlParser->__construct('http://192.168....')
#3 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(62): duncan3dc\Sonos\Speaker->getXml('/xml/device_des...')
#4 /var/www/duncan/vendor/duncan3dc/sonos/src/Network.php(141): duncan3dc\Sonos\Speaker->__construct('192.168.0.30')
#5 /var/www/duncan/vendor/duncan3dc/sonos/src/Network.php(228): duncan3dc\Sonos\Network->getSpeakers()
#6 /var/www/duncan/test.php(6): duncan3dc\Sonos\Network->getControllers()
#7 {main}
  thrown in /var/www/duncan/vendor/duncan3dc/helpers/src/Helper.php on line 664
```

my php test is

```php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;

$sonos = new Network;
$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
    echo $controller->name . " (" . $controller->room . ")\n";
    echo "\tState: " . $controller->getState() . "\n";
}
```

sorry for my bad english im french
thanks

**Comment by duncan3dc** [comment]
@889laurent Your example looks fine, and your English is good. This looks like maybe your speakers have changed IP addresses after being cached. what about if you try to use a very short cache:

```php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;

$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);

$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
    echo $controller->name . " (" . $controller->room . ")\n";
    echo "\tState: " . $controller->getState() . "\n";
}
```

**Comment by 889laurent** [comment]
With your code i have the same result ?


Laurent MARIO Directeur Technique

  [cid:logo20151ce3af]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture11f15af]                                                                                                      [cid:devdurabledf76b9]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : mardi 24 février 2015 09:48
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] exemple (#5)


@889laurent<https://github.com/889laurent> Your example looks fine, and your English is good. This looks like maybe your speakers have changed IP addresses after being cached. what about if you try to use a very short cache:

require_once __DIR__ . "/vendor/autoload.php";

use duncan3dc\Sonos\Network;



$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);



$controllers = $sonos->getControllers();

foreach ($controllers as $controller) {

    echo $controller->name . " (" . $controller->room . ")\n";

    echo "\tState: " . $controller->getState() . "\n";

}

**Comment by duncan3dc** [comment]
@889laurent Which Sonos speakers are you using? eg Play:1? Play:3?

**Comment by 889laurent** [comment]
I have 3 play 3
2 play 1
1 connect amp

I used to sonos class php by djmomo et its work fine


Laurent MARIO Directeur Technique

  [cid:logo201569c585]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1cc36b0]                                                                                                      [cid:devdurablef2cade]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : mardi 24 février 2015 09:58
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] exemple (#5)


@889laurent<https://github.com/889laurent> Which Sonos speakers are you using? eg Play:1? Play:3?

**Comment by duncan3dc** [comment]
@889laurent I only have Play:1's at the moment so this might be to do with the connect amp (it might work differently). Is your room called "Salon"? If so does the following work:

```php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;

$sonos = new Network;
$controller = $sonos->getControllerByRoom("Salon");
echo $controller->name . " (" . $controller->room . ")\n";
echo "\tState: " . $controller->getState() . "\n";
```

**Comment by 889laurent** [comment]
The play of « salon » is a play3

I tried ypur code and I have the same result
PHP Fatal error:  Uncaught exception 'Exception' with message 'couldn't connect to host' in /var/www/duncan/vendor/duncan3dc/helpers/src/Helper.php:664
Stack trace:
#0 /var/www/duncan/vendor/duncan3dc/domparser/src/Parser.php(29): duncan3dc\Helpers\Helper::curl('http://192.168....')
#1 /var/www/duncan/vendor/duncan3dc/domparser/src/XmlParser.php(29): duncan3dc\DomParser\XmlParser->getData('http://192.168....')
#2 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(80): duncan3dc\DomParser\XmlParser->__construct('http://192.168....')
#3 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(62): duncan3dc\Sonos\Speaker->getXml('/xml/device_des...')
#4 /var/www/duncan/vendor/duncan3dc/sonos/src/Network.php(141): duncan3dc\Sonos\Speaker->__construct('192.168.0.30')
#5 /var/www/duncan/vendor/duncan3dc/sonos/src/Network.php(188): duncan3dc\Sonos\Network->getSpeakers()
#6 /var/www/duncan/vendor/duncan3dc/sonos/src/Network.php(249): duncan3dc\Sonos\Network->getSpeakerByRoom('Salon')
#7 /var/www/duncan/test.p2hp(6): duncan3dc\Sonos in /var/www/duncan/vendor/duncan3dc/helpers/src/Helper.php on line 664


Laurent MARIO Directeur Technique

  [cid:logo20153bac7a]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1c12fc6]                                                                                                      [cid:devdurable6fd326]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : mardi 24 février 2015 10:02
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] exemple (#5)


@889laurent<https://github.com/889laurent> I only have Play:1's at the moment so this might be to do with the connect amp (it might work differently). Is your room called "Salon"? If so does the following work:

require_once __DIR__ . "/vendor/autoload.php";

use duncan3dc\Sonos\Network;



$sonos = new Network;

$controller = $sonos->getControllerByRoom("Salon");

echo $controller->name . " (" . $controller->room . ")\n";

echo "\tState: " . $controller->getState() . "\n";

**Comment by duncan3dc** [comment]
@889laurent Ok I think I can see the problem, leave it with me while I work on a fix

**Comment by 889laurent** [comment]
The php code is on raspberry pi.  If you want its possible to connect on it with ssh  the login is pi and the password raspberry.

Your code is in /var/www/duncan

The address is marjoline.no-ip.org on port 222

Laurent MARIO Directeur Technique

  [cid:logo201500c52b]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture132293f]                                                                                                      [cid:devdurablef20e98]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : mardi 24 février 2015 10:02
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] exemple (#5)


@889laurent<https://github.com/889laurent> I only have Play:1's at the moment so this might be to do with the connect amp (it might work differently). Is your room called "Salon"? If so does the following work:

require_once __DIR__ . "/vendor/autoload.php";

use duncan3dc\Sonos\Network;



$sonos = new Network;

$controller = $sonos->getControllerByRoom("Salon");

echo $controller->name . " (" . $controller->room . ")\n";

echo "\tState: " . $controller->getState() . "\n";

**Comment by duncan3dc** [comment]
Thanks @889laurent I will try that.

I've removed the sensitive information from your comment now.

**Comment by duncan3dc** [comment]
Thanks for the access, I can see the problem now, it's due to other upnp devices that are not Sonos, as well as things like the bridge which I haven't used before.

If you look in `/var/www/duncan/duncan3dc.php` you will see some example code that works

**Comment by 889laurent** [comment]
Thanks.
You have patch the code with fix?

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo20158d2041]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1c8c299]                                                                                                      [cid:devdurable8d7ff9]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 24 févr. 2015 à 12:51, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


Thanks for the access, I can see the problem now, it's due to other upnp devices that are not Sonos, as well as things like the bridge which I haven't used before.

If you look in /var/www/duncan/duncan3dc.php you will see some example code that works

**Comment by duncan3dc** [comment]
Yes I have patched your code (`/var/www/duncan/vendor/duncan3dc/sonos/src/Network.php`).

However this is only half of the fix. It is not complete.

I will let you know when there is a new version to install with a full fix

**Comment by 889laurent** [comment]
I tried and it works fine!
Thanks a lot

It was perfect if you add tts function like djmomo phpclass

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo2015763402]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture12c6d3e]                                                                                                      [cid:devdurable6450d0]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 24 févr. 2015 à 13:12, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


Yes I have patched your code (/var/www/duncan/vendor/duncan3dc/sonos/src/Network.php).

However this is only half of the fix. It is not complete.

I will let you know when there is a new version to install with a full fix

**Comment by 889laurent** [comment]
Thanks a lot for your work

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo2015114b1b]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture138355b]                                                                                                      [cid:devdurable8d0d3e]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 24 févr. 2015 à 13:12, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


Yes I have patched your code (/var/www/duncan/vendor/duncan3dc/sonos/src/Network.php).

However this is only half of the fix. It is not complete.

I will let you know when there is a new version to install with a full fix

**Comment by duncan3dc** [comment]
You're welcome, I'm glad you are finding the code useful

**Comment by 889laurent** [comment]
I want a new help for :

-          Record the status of all SONOS in network (state, track, volume,…) (there I need help)

-          Joining  sonos in a group (function addspeaker it s ok for me)

-          Play a message (its ok for me)

-          Remove speaker for the group (function remove speaker its ok for me)

-          Play and stop in initial state before joining the group


Laurent MARIO Directeur Technique

  [cid:logo2015e143ec]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture10c1ae4]                                                                                                      [cid:devdurable54f579]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : mardi 24 février 2015 14:41
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] exemple (#5)


You're welcome, I'm glad you are finding the code useful

**Comment by duncan3dc** [comment]
All of the features available are covered in the [documentation](http://duncan3dc.github.io/sonos/).
If you are having any specific problems with any of the features please feel free to open another issue and I will attempt to help in any way I can

**Comment by 889laurent** [comment]
I tried and open another issue if i have a problem
thanks


Laurent MARIO Directeur Technique

  [cid:logo201544fdcf]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture113a900]                                                                                                      [cid:devdurabled5c6bf]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : mardi 24 février 2015 16:16
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] exemple (#5)


All of the features available are covered in the documentation<http://duncan3dc.github.io/sonos/>.
If you are having any specific problems with any of the features please feel free to open another issue and I will attempt to help in any way I can

**Comment by duncan3dc** [comment]
I've just released version 1.1.0 that has support for non Sonos devices as well as Sonos devices that are not speakers
