### ISSUE TITLE
problems with grouping speakers

### ISSUE THREAD

**Issue by mwi438** [duncan3dc/sonos#53]
Hi,

first of all thanks a lot for this great library!

I'm facing a problem when grouping speakers. What I want to achieve is that always the same two players are grouped together an my favorite radio station starts playing.
Because sometimes my family creates different groups I first remove a speakers to their own and then put the two players together.

This is my script:

``` php
<?php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;
$sonos = new Network;

print "Speakers:\n";
$speakers = $sonos->getSpeakers();
foreach ($speakers as $speaker) {
        print $speaker->room . " - " . $speaker->ip . "\n";
}
print "\n\n\n";

$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
        print $controller->room . " - " . $controller->ip . "\n";
        $subs = $controller->getSpeakers();
        print count($subs) . " Elemente\n";
        foreach ($subs as $sub) {
                print "  - " . $sub->room . " - " . $sub->ip . "\n";
                        if ($sub->room != $controller->room) {
                                $controller->removeSpeaker($sub);
                                print $sub->room . " entfernt\n";
                        }
        }
}
print "\n\n\n";

//Gruppe bauen und SWR3 starten
$s = new Network;
$speak = $s->getSpeakerByRoom("Wohnzimmer");
$cont = $s->getControllerByIP("192.168.251.82");                //Kueche
$cont->addSpeaker($speak);

// Radio einschalten mit URL
use duncan3dc\Sonos\Tracks\Stream;
$stream = new Stream("x-sonosapi-stream:s57730?sid=254&flags=8224&sn=0");
//$controller->useStream($stream)->play();
```

This generally seems to work - i get:
iMac-435:SonosTest martin$ php SonosEG.php 
Speakers:
Wohnzimmer - 192.168.251.84
Küche - 192.168.251.82
Arbeitszimmer - 192.168.251.80
Schlafzimmer - 192.168.251.83
Bad - 192.168.251.81

Küche - 192.168.251.82
2 Elemente
- Wohnzimmer - 192.168.251.84
  Wohnzimmer entfernt
- Küche - 192.168.251.82
  Arbeitszimmer - 192.168.251.80
  1 Elemente
- Arbeitszimmer - 192.168.251.80
  Schlafzimmer - 192.168.251.83
  1 Elemente
- Schlafzimmer - 192.168.251.83
  Bad - 192.168.251.81
  1 Elemente
- Bad - 192.168.251.81

But sometimes - for example when everything was grouped together in party mode and this mode is stopped and every speaker is turned back into its own I get an error when executing my script:

iMac-435:SonosTest martin$ php SonosEG.php 
Speakers:
Wohnzimmer - 192.168.251.84
Küche - 192.168.251.82
Arbeitszimmer - 192.168.251.80
Schlafzimmer - 192.168.251.83
Bad - 192.168.251.81

Wohnzimmer - 192.168.251.84
0 Elemente
Küche - 192.168.251.82
0 Elemente
Arbeitszimmer - 192.168.251.80
0 Elemente
Schlafzimmer - 192.168.251.83
0 Elemente
Bad - 192.168.251.81
0 Elemente

Fatal error: Call to a member function addSpeaker() on a non-object in /Users/martin/Downloads/SonosTest/SonosEG.php on line 48

I noticed that there are no speakers in each controller when looping through the controllers but I also can't add any speaker to the controller - even not "its own" speaker.

Any idea how this can be resolved? Any help is highly appreciated! :-)

Thanks a lot,
Martin

**Comment by duncan3dc** [comment]
Hi Martin,

I've seen similar issues myself, and I think it's related to the caching this library does.

Can you try to the following as a workaround until I get it fixed/improved:
```php

use Doctrine\Common\Cache\ArrayCache;
use duncan3dc\Sonos\Network;

$sonos = new Network(new ArrayCache);
```

**Comment by mwi438** [comment]
Hi Craig,

thanks for your fast reply!
This seems to work for me - it's a bit slower than before but I was not able to reproduce the error using your lines up to now... :-)

Thanks again for your excellent work,
Martin

**Comment by duncan3dc** [comment]
Hi @mwi438, version 2.0 is nearing release now, this should handle the caching issue by default, meaning you can go back to just:
```php
$sonos = new Network;
```
Here's [the documentation](http://duncan3dc.github.io/sonos/v2/) I've got so far, please take a look and let me if you see your issue occur with this version
