### ISSUE TITLE
building my own iTunes genius for Sonos

### ISSUE THREAD

**Issue by lsmith77** [duncan3dc/sonos#55]
this is more a ticket to find like minded people. I want to build a simple solution that I can host on my NAS that will look at the current playing track on my Sonos and queue up a number of matching songs automatically.

the main challenge I guess will be finding an API that will index my personal music collection. if someone knows a useful API for this, that would be awesome.

also if someone wants to collaborate on this or maybe has already build something similar please let me know!

**Comment by duncan3dc** [comment]
I do something similar to this, but not using my personal collection.
Last.fm has a reasonably good API for getting similar songs (eg http://www.last.fm/api/show/artist.getSimilar). So I have a program that looks at artists I've listened to recently, then finds similar artists, and queues them up on Sonos (or creates a playlist) using Spotify.

I've built my own software for managing my personal music collection, but I'm sure there must be something open source out that that has features that could handle the above. My code is very specific to my library and probably wouldn't be easy to release

**Comment by lsmith77** [comment]
ok good to know that something like this is doable but I was quite confident it would be already :)

**Comment by lsmith77** [comment]
@duncan3dc BTW yeah I looked at last.fm too but I guess there is no way to limit the recommendations to songs that one has already played rather than their entire catalog?

in your solution I assume you also have integrated the last.fm into sonos to keep track of what you played on your sonos?

**Comment by duncan3dc** [comment]
Yes, Sonos has support for Last.fm, you can add it (like a music service) and all your plays then scrobble to your Last.fm account.

I've not seen any option limit the recommendations, I guess you'd have to handle that manually

**Comment by lsmith77** [comment]
ok cool .. for now I will try out https://developers.musimap.net
