### ISSUE TITLE
Google music alternate url prefix

### ISSUE THREAD

**Issue by zwigglers** [duncan3dc/sonos#57]
When running this code using Google Music tracks
...
$tracks = $queue->getTracks();
$queue->clear();
$queue->addTracks($tracks);

The track display names would display a URI after removing/re-adding.

Turns out that while a few of my tracks have the URI prefix given in Tracks/Google, most of my tracks use a different prefix. As a temporary fix I've duplicated Tracks/Google with the new prefix. I don't know if there are other prefixes that are being used which might call for a more complete solution

Refer to my commit: https://github.com/zwigglers/sonos/commit/765168c3c39f902e641812a1ffb67f9a0e8d08e6

**Comment by duncan3dc** [comment]
Can you differentiate between the two types of tracks at all?
Is it possible that the existing prefix is used for "uploaded" tracks, and this new one is for tracks that are provided by Google Play Music?

**Comment by zwigglers** [comment]
Great catch. That seems to be it. I tested it on a good number of tracks and it seems to be the pattern.

Prefixes:
_dklxfo- (existing) -- uploaded tracks
A0DvPDnows -- Google Play Music tracks

**Comment by duncan3dc** [comment]
Thanks @zwigglers, I'll see about getting a fix in for this in the next couple of weeks

**Comment by duncan3dc** [comment]
Hi @zwigglers, I don't have a Google Unlimited account, so could you please test out [this branch](https://github.com/duncan3dc/sonos/tree/google-unlimited) and confirm if that's working now?

**Comment by zwigglers** [comment]
Not yet -- I think
`class GoogleUnlimited extends Track`
needs to be
`class GoogleUnlimited extends Google`

**Comment by duncan3dc** [comment]
Sorry about that, I've released the corrected version as [1.9.8](https://github.com/duncan3dc/sonos/releases/tag/1.9.8) now, thanks for your help

**Comment by zwigglers** [comment]
Fixed. Thanks!
