### ISSUE TITLE
Add new model number S12 for Play:1

### ISSUE THREAD

**Issue by mdubbelman** [duncan3dc/sonos#58]
I've just bought a Play:1 and I could not get the API to find my controllers/speakers. After some debugging I found my Play:1 is not in your device list.
Could you please add it to the array of devices in \duncan3dc\Sonos\Device::isSpeaker() ?
The (new?) model is S12 as I found in the device_description.xml :
<img width="559" alt="screen shot 2016-12-27 at 1 01 13 am" src="https://cloud.githubusercontent.com/assets/393123/21487702/8e18a980-cbd0-11e6-92f3-6c8f1ac5bbd8.png">
Thanks!

**Comment by duncan3dc** [comment]
Thanks for the details @mdubbelman, this has been fixed in [1.9.4](https://github.com/duncan3dc/sonos/releases/tag/1.9.4)
