### ISSUE TITLE
I do not Retrieve the speakers or alarm to be launched

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#6]
I do not Retrieve in your API the speakers or alarm to be launched . please help me about this.

**Comment by duncan3dc** [comment]
Please run the following to install an experimental version with support for bridges and other devices:
```bash
composer require duncan3dc/sonos:~1.1-dev
```

After installing that, can you try the following script:
```php
use duncan3dc\Sonos\Network;
require __DIR__ . "/vendor/autoload.php";

$sonos = new Network;
$alarms = $sonos->getAlarms();

foreach ($alarms as $alarm) {
    echo "Alarm ID: {$alarm->getId()}\n";
    echo "Time: {$alarm->getTime()}\n";
    echo "Duration: {$alarm->getDuration()}\n";
    echo "Volume: {$alarm->getVolume()}\n";
    echo "Frequency: {$alarm->getFrequencyDescription()}\n";
    echo "-------------------------------------------\n";
}
```

**Comment by 889laurent** [comment]
Your exemple works with your actual php , but I do not find the name of speaker of alarm !

Copy screen
Alarm ID: 44
Time: 07:30
Duration: 15
Volume: 24
Frequency: Weekdays
-------------------------------------------
Alarm ID: 46
Time: 07:20
Duration: 15
Volume: 20
Frequency: Tues
-------------------------------------------
Alarm ID: 48
Time: 06:20
Duration: 15
Volume: 20
Frequency: Wed,Thurs,Fri,Sat
-------------------------------------------


Laurent MARIO Directeur Technique

  [cid:logo2015f5efdb]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1a96b33]                                                                                                      [cid:devdurable29b49b]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : jeudi 26 février 2015 10:02
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] I do not Retrieve the speakers or alarm to be launched (#6)


Please run the following to install an experimental version with support for bridges and other devices:

composer require duncan3dc/sonos:~1.1-dev

After installing that, can you try the following script:

use duncan3dc\Sonos\Network;

require __DIR__ . "/vendor/autoload.php";



$sonos = new Network;

$alarms = $sonos->getAlarms();



foreach ($alarms as $alarm) {

    echo "Alarm ID: {$alarm->getId()}\n";

    echo "Time: {$alarm->getTime()}\n";

    echo "Duration: {$alarm->getDuration()}\n";

    echo "Volume: {$alarm->getVolume()}\n";

    echo "Frequency: {$alarm->getFrequencyDescription()}\n";

    echo "-------------------------------------------\n";

}

**Comment by duncan3dc** [comment]
Ok I understand. That feature is not available yet, I will work on it and let you know when it is

**Comment by 889laurent** [comment]
Ok thanks


Laurent MARIO Directeur Technique

  [cid:logo20155cafe7]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1aed668]                                                                                                      [cid:devdurable053350]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



De : Craig Duncan [mailto:notifications@github.com]
Envoyé : jeudi 26 février 2015 10:42
À : duncan3dc/sonos
Cc : laurent MARIO
Objet : Re: [sonos] I do not Retrieve the speakers or alarm to be launched (#6)


Ok I understand. That feature is not available yet, I will work on it and let you know when it is

**Comment by 889laurent** [comment]
i tried your experimental php class (composer require duncan3dc/sonos:~1.1-dev) and i have this error result !

PHP Fatal error:  Call to undefined method duncan3dc\Sonos\Device::logger() in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php on line 58

i do réinstall original version or i tried another solution !

**Comment by duncan3dc** [comment]
1.1-dev should be working again, hopefully I'll be doing a stable release very soon

**Comment by duncan3dc** [comment]
This feature is available in version 1.1.0:
```php
$alarm->getRoom();           # Returns the room's UUID
$alarm->getSpeaker();        # Returns a Speaker instance for the room
$alarm->getSpeaker()->room;  # Get the room's name
```

I'll be updating the documentation shortly

**Comment by 889laurent** [comment]
Good job
Thanks

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo2015cf1cf5]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture11c535f]                                                                                                      [cid:devdurable194896]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 27 févr. 2015 à 18:58, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


This feature is available in version 1.1.0:

$alarm->getRoom();           # Returns the room's UUID
$alarm->getSpeaker();        # Returns a Speaker instance for the room
$alarm->getSpeaker()->room;  # Get the room's name

I'll be updating the documentation shortly
