### ISSUE TITLE
Adding spotify tracks to queue performance

### ISSUE THREAD

**Issue by xIntern** [duncan3dc/sonos#61]
Hello and thanks for this awesome library!

Im having some performance issues where PHP will reach its default max execution time when adding spotify uris to the queue.

I timed the functions to get these results:
Add 1 spotify uri(s): 0.30468702316284 seconds
(Soap: 0.28796887397766 seconds)
Add 86 spotify uri(s): 41.789011001587 seconds
(Soap: 41.768350124359 seconds)

Add 1 local uri(s): 0.037302017211914 seconds
(Soap: 0.021466970443726 seconds)
Add 170 local uri(s): 4.3112471103668 seconds
(Soap: 4.3003876209259 seconds)

Is it possible to increase performance when adding spotify tracks?

Thanks!

**Comment by duncan3dc** [comment]
Thanks for your report, I'll take a look at what's causing the performance drop and see if it can be improved

**Comment by duncan3dc** [comment]
As long as you're using `addTracks()` (and not calling `addTrack()` repeatedly) it doesn't look like there's anything we can do to improve the speed unfortunately.

If we can get Spotify "groups" of tracks (such as albums, playlists, etc) working (#56) then it will be quicker, but if you just want to add 50 odd tracks that aren't part of any existing "group" then it'll always be this slow sorry
