### ISSUE TITLE
interrupt does not continue line in playback 

### ISSUE THREAD

**Issue by ackonsult** [duncan3dc/sonos#64]
When interrupt is called while playing line in (e.g. of a Sonos soundbar), sound will not continue after the interrupting track is finished.

**Comment by ackonsult** [comment]
I added this piece of code to isStreaming():

    # SPDIF
    if (substr($uri, 0, 18) === "x-sonos-htastream:") {
        return true;
    }

Now interrupting works as expected.

**Comment by duncan3dc** [comment]
Thanks for the report @ackonsult, I think I noticed this bug when I was working on 2.0 earlier this week.
I'll see if I can get it fixed in the next couple of days for you

**Comment by duncan3dc** [comment]
This is fixed in [1.9.7](https://github.com/duncan3dc/sonos/releases/tag/1.9.7)
