### ISSUE TITLE
Avoid disk write operations

### ISSUE THREAD

**Issue by Paco777** [duncan3dc/sonos#65]
Hello,
I'm using the library on a web server stored on a dedicated Raspberry PI.
Thank you for all your hard work.

After about a year of use, the SD card somehow broke, and it is does not accept write operations anymore.
I then replaced it.

I've read that SD cards have a limited number of possible write operations, so I'm trying to reduce the number of those, if possible.

I'm initializing the sonos library like this :
    $cache = new \Doctrine\Common\Cache\FilesystemCache("/tmp/sonos-cache");
    $cache->deleteAll();
    $sonos = new Network($cache);

I noticed that I had some problems with the default cache not being consistent most of the time. This is why I had to deleteAll() at every use of the library (each time my php is called : about 10 times a day)

I looked at my /tmp/sonos-cache folder, and I found hundreds of thousands files and directories, taking more than 2 Gb.

So my question is :
Since I don't really need disk caching (because, I start from scratch at each call), Is there a way I can remove it, to avoid any disk write operations ?

thank you :)

**Comment by duncan3dc** [comment]
Hi @Paco777, yes you can [control the cache](http://duncan3dc.github.io/sonos/setup/#cache) used by the library. If you don't want to cache anything to disk then using [array cache](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html) sounds like a good idea:
```php
$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);
```

**Comment by Paco777** [comment]
Perfect.
Thank you @duncan3dc !
