### ISSUE TITLE
Error running from web call

### ISSUE THREAD

**Issue by nelis249** [duncan3dc/sonos#66]
I'm at a loss. Implementation seems awesome. I simply created a test page with the following on Apache 2.4 and PHP 5.4, (aka sample):

```php
require_once __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;
$sonos = new Network();
$speakers = $sonos->getSpeakers();
foreach ($speakers as $speaker) {
	echo $speaker->name . " (" . $speaker->room . ")\n";
}
```

Running command line: php test.php runs fine. Reports correctly. Is very responsive.
Running from apache through a web call: http://blahblah/test.php results in:
 Error: cURL error 7: Failed to connect to 192.168.1.54 port 1400: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I put a var_dump in the CurlHandler.php -> __invoke method. I then repeated both test cases; CLI and web call and found two different dump outputs. The CLI var dump didn't have the IP '192.168.1.54' at all and the web call did. This is odd as the .54 address isn't even on the network. This makes me think 'seems like a cache issue'. But why would the CLI call and the web call have different cache's? I then changed the code to the delete cache (literally used the web doc code).

```php
$cache = new \Doctrine\Common\Cache\FilesystemCache("/tmp/sonos-cache");
$cache->deleteAll();
$sonos = new Network($cache);
```

With this code both the CLI call and the web call reported "Error: No devices found on the current network".  Seems like there something I'm missing with the cache but in the end game the CLI and web api calling should result the same output regardless of the cache or not. In my instance it seems like the CLI is working (without the cache code above) but the web call is using some unkown cache or variables which result in failure (again referencing the IP 192.168.1.54 witch doesn't exist.

**Comment by duncan3dc** [comment]
Hi @nelis249, sorry the library isn't working as you expect.
It's possible for PHP to use a different [configuration file](http://php.net/manual/en/configuration.file.php) for the CLI and the web, which sounds like what is going on here.

Could you check what `sys_get_temp_dir()` returns on both CLI and web? We use that to determine the default cache location, so maybe that is configured differently on your system.

**Comment by ackonsult** [comment]
I had a similar problem once, when my subwoofer, wich is part of a group was powered off. The Sonos systems itself works fine, but the library refuses to work (timeout...).

**Comment by duncan3dc** [comment]
Hi @ackonsult, that will just be that the subwoofer was still in the cached list of devices, but obviously attempts to communicate with it would fail. Version 2.0 will fix these problems by not caching by default, and making it a developer decision how and when to cache based on their environment

**Comment by nelis249** [comment]
@duncan3dc  yea that was it. Since it's running under Apache versus CLI as me the temp location was different. I copied over the cache from my profile and works from web just fine. Thank you for the assist!
