### ISSUE TITLE
Error calling setVolume on speaker with fixed output

### ISSUE THREAD

**Issue by tobiaskluge** [duncan3dc/sonos#68]
Some speaker allow to define the output volume as a fixed value (e.g. for the SONOS Amp). When the SetVolume is called, this leads to a 501 error from SONOS since the output value cannot be changed.

For example, in the Interrupt function, the volume is restored and so causes the whole function call to break.

Maybe a solution would be to check in the SetVolume function if the speaker allows to set the volume and only set if possible.

**Comment by duncan3dc** [comment]
Hi @tobiaskluge, I presume you mean the Amp __does not__ allow you to set a volume?

I'll take a look, I'll probably need some debug information from you at some point as I don't have an Amp to test with, thanks

**Comment by duncan3dc** [comment]
Hi @tobiaskluge, I did some digging online and it appears that the `CONNECT:AMP` does have volume buttons on, so I'm a bit confused about this issue. Could you explain the problem?

**Comment by duncan3dc** [comment]
I presume you resolved your problem, but if not please feel free to re-open the issue
