### ISSUE TITLE
Add method to launch playlist by it's uri

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#70]
Hi,

Do you think it's possible to add method that launch playlist by use her URI. 

I make some test on it and it's seem more performante than add track by track to queue.

Thank in advance.

**Comment by duncan3dc** [comment]
Hi @zoic21, do you mean Sonos playlists? If so that should be possible, and yes would perform much better. Let me take a look if I can fit it into 2.0

**Comment by duncan3dc** [comment]
This was done in #98 by @0bp and will be part of the next release
