### ISSUE TITLE
Accents are sent wrongly to TTSProvider

### ISSUE THREAD

**Issue by Zegorax** [duncan3dc/sonos#71]
If I try to send the text "Le serveur va redémarrer", the TTS will say : "Le serveur va redA©marer".

So the accents are not sent as plain text.

**Comment by duncan3dc** [comment]
Hi @Zegorax, thanks for your interest in this library. Please could you provide a short script to reproduce the problem?

**Comment by duncan3dc** [comment]
I'm unable to re-produce this sorry @Zegorax. If you can provide a short script that demonstrates the problem I'd be happy to look into it for you. Please raise it over at [duncan3dc/speaker](https://github.com/duncan3dc/speaker/issues) where the TTS is handled
