### ISSUE TITLE
Installation issue using composer.

### ISSUE THREAD

**Issue by ALROCHARARI** [duncan3dc/sonos#74]
Dear,

Please see screen capture of issue encountered during installation attempt.
Not sure this is an issue with your work.  Most than probably my mistake.
Thanks in advance for your kind support.

Best regards,
Raoul
![sonos issue 1](https://user-images.githubusercontent.com/26901310/30986700-a127829c-a494-11e7-9b30-32f90004f6ee.jpg)

**Comment by duncan3dc** [comment]
Can you try the following composer command:
```sh
composer require duncan3dc/sonos --update-with-dependencies
```
If that doesn't work can you paste your `composer.json` here so I can try and figure out what's clashing

**Comment by ALROCHARARI** [comment]
Thanks for your quick answer.

See result of new trial.
![sonos issue 2](https://user-images.githubusercontent.com/26901310/30987243-99c95d3e-a496-11e7-88bd-1e6f628f0cc9.jpg)

This is the copy of composer.json file:
{
    "name": "duncan3dc/sonos",
    "type": "library",
    "description": "Control Sonos speakers using a simple API",
    "keywords": ["sonos","upnp","streaming"],
    "homepage": "https://github.com/duncan3dc/sonos",
    "license": "Apache-2.0",
    "authors": [{
        "name": "Craig Duncan",
        "email": "git@duncanc.co.uk",
        "homepage": "https://github.com/duncan3dc",
        "role": "Developer"
    }],
    "require": {
        "doctrine/cache": "^1.4",
        "duncan3dc/domparser": "^1.4.1",
        "duncan3dc/speaker": "^0.7.0",
        "guzzlehttp/guzzle": "^6.0",
        "league/flysystem": "^1.0",
        "psr/log": "1.0.0",
        "ext-soap": "*",
        "ext-sockets": "*",
        "php": "^5.6|^7.0",
        "duncan3dc/sonos": "1.9.8"
    },
    "require-dev": {
        "duncan3dc/object-intruder": "^0.1.0",
        "mockery/mockery": "^0.9.4",
        "phpunit/phpunit": "^5.7.14",
        "satooshi/php-coveralls": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "duncan3dc\\Sonos\\": "src/",
            "duncan3dc\\SonosTests\\": "tests/"
        }
    }
}

Thanks again for time on this case.

Br,
Raoul

**Comment by duncan3dc** [comment]
That's the `composer.json` of this library, are you trying to use the library or work on it?
* If you are using it then you don't need to clone or fork it, from an empty directory you can just install it using the command you originally tried.
* If you want to work on the library itself, then you just use `composer update` to install all the relevant dependencies

**Comment by ALROCHARARI** [comment]
Thanks for great help.

Problem solved.

I thought it was necessary to clone first.

Best regards,
Raoul
