### ISSUE TITLE
Develop same libraries for python

### ISSUE THREAD

**Issue by ALROCHARARI** [duncan3dc/sonos#75]
Dear,

(Enhancement suggestion)

I personally find this sonos Library of great added value.  
This is exactly fullfilling my expectations.

Do you know if similar library is existing for Python or if you (could) plan to make one?

Thanks for your feedback.

Best regards,
Raoul

**Comment by duncan3dc** [comment]
Hi Raoul, yes there is a library available for Python, it's called SoCo
https://github.com/SoCo/SoCo
