### ISSUE TITLE
Voxygen TTS provider no longer works

### ISSUE THREAD

**Issue by rlerdorf** [duncan3dc/sonos#77]
Most of the URLs referenced in the Voxygen code don't work anymore.
Even simple things like http://voxygen.fr/voices.json
I tried clicking around a bit to find the updated ones, but hit a lot of 404s even just clicking on links on Voxygen's own site, so I am not sure what is going on with that.

**Comment by duncan3dc** [comment]
Hi Rasmus,

Unfortunately Voxygen removed access to the service we were taking advantage of (duncan3dc/speaker#6).

We've experienced quite a few issues with the free services, so we added support for an offline version on Linux: http://duncan3dc.github.io/speaker/providers/picotts/

If you know of any free online tts services please let me know and I'd be happy to add support for them to [duncan3dc/speaker](https://github.com/duncan3dc/speaker)

**Comment by duncan3dc** [comment]
[Responsive Voice](http://duncan3dc.github.io/speaker/providers/responsive-voice/) is already available over at [duncan3dc/speaker](https://github.com/duncan3dc/speaker)
