### ISSUE TITLE
error with play function

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#8]
i tried this code
```php
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Controller;
$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);
$controllers = $sonos->getControllers();
 foreach ($controllers as $controller) {
     if ($controller->getState() !== Controller::STATE_PLAYING) {
         $controller->play();
     }
 }
```

and i have this result

```
PHP Fatal error:  Uncaught exception 'duncan3dc\Sonos\Exceptions\SoapException' with message 'UPnPError: 701' in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php:115
Stack trace:
#0 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(104): duncan3dc\Sonos\Device->soap('AVTransport', 'Play', Array)
#1 /var/www/duncan/vendor/duncan3dc/sonos/src/Controller.php(184): duncan3dc\Sonos\Speaker->soap('AVTransport', 'Play', Array)
#2 /var/www/duncan/play.php(11): duncan3dc\Sonos\Controller->play()
#3 {main}
  thrown in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php on line 115
```

i have same result with pause, stop ,...

**Comment by duncan3dc** [comment]
Do you have something queued up for every controller?

701 is usually something like invalid state, maybe an empty queue would cause that

**Comment by 889laurent** [comment]
I think it's a problem of memory buffer. If I run the same command on a single SONOS it works

**Comment by duncan3dc** [comment]
That's probably because the single SONOS you are trying it on works, but it's one of the others that is failing.

Did you check all the queues? You could add some `echo` statements within the `foreach` loop to see which controller is failing, and how many items are in it's queue

**Comment by 889laurent** [comment]
i have tried with this code

#!/usr/bin/env php
<?php

require __DIR__ . "/vendor/autoload.php";
use duncan3dc\Sonos\Network;
use duncan3dc\Sonos\Controller;
$cache = new \Doctrine\Common\Cache\FilesystemCache("/tmp/sonos-cache");
 $cache->deleteAll();
 $sonos = new Network($cache);


$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
$queue =$controller->getQueue();
$nb = $queue->count();
        echo $controller->getStateName(). " " . $controller->room . " " . $cont$
        $controller->pause();

 }
  the result is
STOPPED Chambre coline 50 138
PHP Fatal error:  Uncaught exception 'duncan3dc\Sonos\Exceptions\SoapException' with message 'UPnPError: 701' in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php:115
Stack trace:
#0 /var/www/duncan/vendor/duncan3dc/sonos/src/Speaker.php(104): duncan3dc\Sonos\Device->soap('AVTransport', 'Pause', Array)
#1 /var/www/duncan/vendor/duncan3dc/sonos/src/Controller.php(195): duncan3dc\Sonos\Speaker->soap('AVTransport', 'Pause')
#2 /var/www/duncan/play.php(17): duncan3dc\Sonos\Controller->pause()
#3 {main}
  thrown in /var/www/duncan/vendor/duncan3dc/sonos/src/Device.php on line 115

if i delete the ligne $controller->pause(); i have this résult
PAUSED_PLAYBACK Salle de bains 50 2089
PAUSED_PLAYBACK pergola 50 1
STOPPED Chambre coline 50 138
PAUSED_PLAYBACK Salon 50 2
PAUSED_PLAYBACK Salle de bains2 50 8
STOPPED Chambre marjorie 50 4334

**Comment by duncan3dc** [comment]
That error is because you are trying to pause a room that is stopped, which is why the `701 Invalid State` error is thrown.

What you if you change the `pause()` back to the play code you had before, what output do you get then?

**Comment by 889laurent** [comment]
if i replace pause by play its ok
résult
PLAYING Salle de bains2 0 8
PLAYING Salle de bains 0 2089
PLAYING Salon 0 2
PLAYING Chambre marjorie 0 4334
STOPPED Chambre coline 0 138
PLAYING pergola 0 1

but if i tried pause there are an error with SONOS with state STOPPED !

**Comment by 889laurent** [comment]
how played a SONOS with state STOPPED ?

**Comment by duncan3dc** [comment]
You can't pause a SONOS that is stopped. You need to check the current state `getState()` before attempting to play/pause/stop/etc

**Comment by 889laurent** [comment]
ok for pause a SONOS with state STOPPED (its logical) but how play a sonos with state STOPPED ? its not works !

**Comment by duncan3dc** [comment]
That's strange, what is the output of the following script:

```php
$sonos = new Network;

$controllers = $sonos->getControllers();
foreach ($controllers as $controller) {
    echo "--------------------------------------------\n";
    echo "ip:    {$controller->ip}\n";
    echo "name:  {$controller->name}\n";
    echo "room:  {$controller->room}\n";
    echo "queue: " . count($controller->getQueue()) . "\n";
    echo "state: " . $controller->getStateName() . "\n";
    if ($controller->getState() !== Controller::STATE_PLAYING) {
        echo "Start Playing...\n";
        $controller->play();
    }
}
```

**Comment by 889laurent** [comment]
résult

--------------------------------------------
ip:    192.168.0.86
name:  192.168.0.86 - Sonos PLAY:1
room:  Salle de bains
queue: 2089
state: PAUSED_PLAYBACK
Start Playing...
--------------------------------------------
ip:    192.168.0.85
name:  192.168.0.85 - Sonos PLAY:3
room:  Chambre marjorie
queue: 4334
state: PAUSED_PLAYBACK
Start Playing...
--------------------------------------------
ip:    192.168.0.57
name:  192.168.0.57 - Sonos PLAY:1
room:  Salle de bains2
queue: 8
state: PAUSED_PLAYBACK
Start Playing...
--------------------------------------------
ip:    192.168.0.32
name:  192.168.0.32 - Sonos PLAY:3
room:  Chambre coline
queue: 138
state: STOPPED
Start Playing...
--------------------------------------------
ip:    192.168.0.46
name:  192.168.0.46 - Sonos PLAY:3
room:  pergola
queue: 1
state: STOPPED
Start Playing...
--------------------------------------------
ip:    192.168.0.47
name:  192.168.0.47 - Sonos PLAY:3
room:  Salon
queue: 2
state: PAUSED_PLAYBACK
Start Playing...

**Comment by duncan3dc** [comment]
So no errors? Is there a problem?

**Comment by 889laurent** [comment]
the second result after play

--------------------------------------------
ip:    192.168.0.32
name:  192.168.0.32 - Sonos PLAY:3
room:  Chambre coline
queue: 138
state: STOPPED
Start Playing...
--------------------------------------------
ip:    192.168.0.47
name:  192.168.0.47 - Sonos PLAY:3
room:  Salon
queue: 2
state: PLAYING
--------------------------------------------
ip:    192.168.0.86
name:  192.168.0.86 - Sonos PLAY:1
room:  Salle de bains
queue: 2089
state: PLAYING
--------------------------------------------
ip:    192.168.0.46
name:  192.168.0.46 - Sonos PLAY:3
room:  pergola
queue: 1
state: PLAYING
--------------------------------------------
ip:    192.168.0.85
name:  192.168.0.85 - Sonos PLAY:3
room:  Chambre marjorie
queue: 4334
state: PLAYING
--------------------------------------------
ip:    192.168.0.57
name:  192.168.0.57 - Sonos PLAY:1
room:  Salle de bains2
queue: 8
state: PLAYING


the sonos play 3 192.168.0.32 is in state STOPPED after play ?

**Comment by duncan3dc** [comment]
Are the contents of the queue available? Maybe Sonos is failing to play the tracks queued because they can not be found. Have you tried to play that queue using the Official Sonos App?

**Comment by 889laurent** [comment]
the contents of my playlist in this SONOS is not ok. That the problem.

Thanks for your help. 
Have you avanced about connect and connect amp ? in first time i want to try the model of connect amp in your code device.php

'''return in_array($model, ["S1", "S3", "S5"], true);'''
what the model of connect amp and connect ?

**Comment by duncan3dc** [comment]
The bridge is `'ZB100'`, the connect is `'ZP90'` and the connect amp is `'ZP120'`
