### ISSUE TITLE
Unable to connect to Sonos Network

### ISSUE THREAD

**Issue by brino** [duncan3dc/sonos#80]
No matter what I try I can't seem to connect to the network... by that I mean if I dump the Network object after instantiation, there are no speakers.

Is there some kind of trick? Do I need to do something to figure out the proper multicast address? I've tried looking up the IP's of the 3 controllers we have and using one of those as the multicast address and tried various wired/wireless network connections and interfaces ... no matter what i do it doesn't seem to connect!

Any help would be greatly appreciated!

**Comment by duncan3dc** [comment]
Hi @brino, sorry for the delay in looking at your issue.

I presume you're able to use your speakers from the official Sonos app?

Could you please [enable logging](http://duncan3dc.github.io/sonos/logging/) and attach the output you get when trying to use your speakers

**Comment by brino** [comment]
thanks for the response I was able to figure it out ... just instantiating the Network object does not initiate discovery ... you have to use getController() or similar method to initiate the discovery process. After I figured that out it worked great! thanks and keep up the good work!
