### ISSUE TITLE
Add abillity to edit alarm stream / playlist

### ISSUE THREAD

**Issue by phoniclynx** [duncan3dc/sonos#82]
Can you please add the ability to specify a stream or playlist in the Alarm section. So far all you can do is edit it in the app, find it's id then modify the alarm time and state.

**Comment by duncan3dc** [comment]
Hi @phoniclynx, that sounds like a good idea, I'll look into it when I get some time and see if I can put something together for you

**Comment by phoniclynx** [comment]
Hey, @duncan3dc cheers sounds good... I guess the same goes for the Snooze Alerts option.

Don't forget it should go for Streams as well as Play Lists.

**Comment by duncan3dc** [comment]
This has been done in a566c2015059144ace97cce7a0186a0172efdb51 and will be part of the next release
