### ISSUE TITLE
Sonos One and Alarm can't find speaker error

### ISSUE THREAD

**Issue by phoniclynx** [duncan3dc/sonos#83]
Just bought a couple of Sonos One speakers and tried to run the alarm functions using your lib. However, if I call the alarm with the Sonos app set to the new speakers I get the error:
`
Fatal error:  Uncaught RuntimeException: Unable to find a speaker for this alarm in /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php:130
Stack trace:
#0 /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php(77): duncan3dc\Sonos\Alarm->getSpeaker()
#1 /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php(657): duncan3dc\Sonos\Alarm->soap('AlarmClock', 'UpdateAlarm', Array)
#2 /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php(181): duncan3dc\Sonos\Alarm->save()
#3 /var/www/html/sonoscontroller.php(19): duncan3dc\Sonos\Alarm->setTime('17:04')
#4 /var/www/html/GoogleAlarm/quickstart.php(238): sonosAlarmUpdate(13156, '17:04', false, '15')
#5 {main}
  thrown in /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php on line 130`

but if I create a 'party mode' in the Sonos app and point it at the older play 5's it will play through all 4 speakers. Unfortunately, during the day the party often get's turned off leaving the Sonos ones in their own alarm and then when you run the script you get that error again. Leaving me with no alarm.

**Comment by duncan3dc** [comment]
Hi @phoniclynx, please could you reproduce the "Unable to find speaker for this alarm" error with logging enabled and post the result in a [gist](https://gist.github.com/)?

You can do this using `monolog` like so:
``` sh
composer require monolog/monolog
```

``` php
$logger = new \Monolog\Logger("sonos");
$handler = new \Monolog\Handler\StreamHandler("php://stdout", \Monolog\Logger::DEBUG);
$logger->pushHandler($handler);
$sonos->setLogger($logger);
```

**Comment by phoniclynx** [comment]
i've tried running and installing monolog:
`nat@HomeAuto:/var/www/html $ php composer.phar require monolog/monolog
Using version ^1.23 for monolog/monolog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files`

And I get no output when I put in those lines? only the error from before which is logged above

**Comment by duncan3dc** [comment]
You're running this through a webserver? Try using `php://output` instead of `php://stdout`

**Comment by phoniclynx** [comment]
AHHH.. I believe this is more useful to you:
[2018-05-20 00:27:23] sonos.INFO: creating speaker instances [] []
[2018-05-20 00:27:23] sonos.INFO: getting device info from cache [] []
[2018-05-20 00:27:23] sonos.NOTICE: Getting topology info from: http://192.168.2.156:1400/status/topology [] []
[2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.156:1400/xml/device_description.xml [] []
[2018-05-20 00:27:23] sonos.DEBUG: 192.168.2.156 model: S6 [] []
[2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.156:1400/xml/device_description.xml [] []
[2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.210:1400/xml/device_description.xml [] []
[2018-05-20 00:27:23] sonos.DEBUG: 192.168.2.210 model: S6 [] []
[2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.210:1400/xml/device_description.xml [] []
[2018-05-20 00:27:23] sonos.INFO: sending soap request to: http://192.168.2.156:1400/AlarmClock/Control [] []
[2018-05-20 00:27:23] sonos.DEBUG: REQUEST:  0  [] []
[2018-05-20 00:27:23] sonos.DEBUG: RESPONSE: <Alarms><Alarm ID="12" StartTime="22:30:00" Duration="04:00:00" Recurrence="DAILY" Enabled="1" RoomUUID="RINCON_7828CAC16B8C01400" ProgramURI="x-sonosapi-stream:s108661?sid=254&amp;flags=8224&amp;sn=0" ProgramMetaData="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;R:0/0/6&quot; parentID=&quot;R:0/0&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Koffee&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65031_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;" PlayMode="SHUFFLE" Volume="2" IncludeLinkedZones="0"/><Alarm ID="14" StartTime="17:04:00" Duration="02:00:00" Recurrence="ONCE" Enabled="0" RoomUUID="RINCON_7828CAC16B8C01400" ProgramURI="x-sonosapi-stream:s17634?sid=254&amp;flags=8224&amp;sn=0" ProgramMetaData="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;R:0/0/17&quot; parentID=&quot;R:0/0&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Nova 100 100.3 (Top 40 &amp;amp; Pop Music)&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65031_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;" PlayMode="SHUFFLE" Volume="15" IncludeLinkedZones="1"/><Alarm ID="13156" StartTime="07:00:00" Duration="03:00:00" Recurrence="ONCE" Enabled="0" RoomUUID="RINCON_7828CAC16B8C01400" ProgramURI="x-rincon-buzzer:0" ProgramMetaData="" PlayMode="SHUFFLE" Volume="5" IncludeLinkedZones="1"/></Alarms>RINCON_5CAAFD09469C01400:13159 [] []

**Comment by phoniclynx** [comment]
Interesting that 192.168.2.156 is the Sonos Play 5, and the SonosOne's are 192.168.2.153 and 192.168.2.214

**Comment by duncan3dc** [comment]
Did you copy that from the browser? It looks like the XML might be hidden, could you try viewing the page source and seeing if there's more info being written to the screen?

**Comment by phoniclynx** [comment]
| <pre>Mon 18:45 @ Training<br/><br/>Distance: <b>10.7 km</b><br>Travel time duration: <b>11 mins</b><br/><br>Wake Up at: 17:14<br>Lights on at: Mon 17:04<br/><br/>NO LIGHTS Today[2018-05-20 00:27:23] sonos.INFO: creating speaker instances [] []
-- | --
  | [2018-05-20 00:27:23] sonos.INFO: getting device info from cache [] []
  | [2018-05-20 00:27:23] sonos.NOTICE: Getting topology info from: http://192.168.2.156:1400/status/topology [] []
  | [2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.156:1400/xml/device_description.xml [] []
  | [2018-05-20 00:27:23] sonos.DEBUG: 192.168.2.156 model: S6 [] []
  | [2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.156:1400/xml/device_description.xml [] []
  | [2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.210:1400/xml/device_description.xml [] []
  | [2018-05-20 00:27:23] sonos.DEBUG: 192.168.2.210 model: S6 [] []
  | [2018-05-20 00:27:23] sonos.INFO: getting xml from cache: http://192.168.2.210:1400/xml/device_description.xml [] []
  | [2018-05-20 00:27:23] sonos.INFO: sending soap request to: http://192.168.2.156:1400/AlarmClock/Control [] []
  | [2018-05-20 00:27:23] sonos.DEBUG: REQUEST: <?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:schemas-upnp-org:service:AlarmClock:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:ListAlarms><InstanceID xsi:type="xsd:string">0</InstanceID></ns1:ListAlarms></SOAP-ENV:Body></SOAP-ENV:Envelope>  [] []
  | [2018-05-20 00:27:23] sonos.DEBUG: RESPONSE: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:ListAlarmsResponse xmlns:u="urn:schemas-upnp-org:service:AlarmClock:1"><CurrentAlarmList>&lt;Alarms&gt;&lt;Alarm ID=&quot;12&quot; StartTime=&quot;22:30:00&quot; Duration=&quot;04:00:00&quot; Recurrence=&quot;DAILY&quot; Enabled=&quot;1&quot; RoomUUID=&quot;RINCON_7828CAC16B8C01400&quot; ProgramURI=&quot;x-sonosapi-stream:s108661?sid=254&amp;amp;flags=8224&amp;amp;sn=0&quot; ProgramMetaData=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;R:0/0/6&amp;quot; parentID=&amp;quot;R:0/0&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Koffee&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.audioBroadcast&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON65031_&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot; PlayMode=&quot;SHUFFLE&quot; Volume=&quot;2&quot; IncludeLinkedZones=&quot;0&quot;/&gt;&lt;Alarm ID=&quot;14&quot; StartTime=&quot;17:04:00&quot; Duration=&quot;02:00:00&quot; Recurrence=&quot;ONCE&quot; Enabled=&quot;0&quot; RoomUUID=&quot;RINCON_7828CAC16B8C01400&quot; ProgramURI=&quot;x-sonosapi-stream:s17634?sid=254&amp;amp;flags=8224&amp;amp;sn=0&quot; ProgramMetaData=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;R:0/0/17&amp;quot; parentID=&amp;quot;R:0/0&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Nova 100 100.3 (Top 40 &amp;amp;amp; Pop Music)&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.audioBroadcast&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON65031_&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot; PlayMode=&quot;SHUFFLE&quot; Volume=&quot;15&quot; IncludeLinkedZones=&quot;1&quot;/&gt;&lt;Alarm ID=&quot;13156&quot; StartTime=&quot;07:00:00&quot; Duration=&quot;03:00:00&quot; Recurrence=&quot;ONCE&quot; Enabled=&quot;0&quot; RoomUUID=&quot;RINCON_7828CAC16B8C01400&quot; ProgramURI=&quot;x-rincon-buzzer:0&quot; ProgramMetaData=&quot;&quot; PlayMode=&quot;SHUFFLE&quot; Volume=&quot;5&quot; IncludeLinkedZones=&quot;1&quot;/&gt;&lt;/Alarms&gt;</CurrentAlarmList><CurrentAlarmListVersion>RINCON_5CAAFD09469C01400:13159</CurrentAlarmListVersion></u:ListAlarmsResponse></s:Body></s:Envelope> [] []
  | <pre></pre><br />
  | <b>Fatal error</b>:  Uncaught RuntimeException: Unable to find a speaker for this alarm in /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php:130
  | Stack trace:
  | #0 /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php(77): duncan3dc\Sonos\Alarm-&gt;getSpeaker()
  | #1 /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php(657): duncan3dc\Sonos\Alarm-&gt;soap('AlarmClock', 'UpdateAlarm', Array)
  | #2 /var/www/html/vendor/duncan3dc/sonos/src/Alarm.php(181): duncan3dc\Sonos\Alarm-&gt;save()
  | #3 /var/www/html/sonoscontroller.php(23): duncan3dc\Sonos\Alarm-&gt;setTime('17:04')
  | #4 /var/www/html/GoogleAlarm/quickstart.php(238): sonosAlarmUpdate(13156, '17:04', false, '15')
  | #5 {main}
  | thrown in <b>/var/www/html/vendor/duncan3dc/sonos/src/Alarm.php</b> on line <b>130</b><br />
  |

**Comment by duncan3dc** [comment]
One last tweak, could you disable caching so that all the speaker information is fetched from the devices:
```php
$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);
```

**Comment by phoniclynx** [comment]
<script src="https://gist.github.com/phoniclynx/332ce17c41408db095035838ce55de07.js"></script>

**Comment by phoniclynx** [comment]
https://gist.github.com/phoniclynx/332ce17c41408db095035838ce55de07

**Comment by duncan3dc** [comment]
It looks like that's a different error now, so the original one was likely caused by some invalid cache, have you recently added these new speakers?

The error there looks like it might be because you've already got an alarm at that time? Could you check that? And maybe try to set it for a different time?

**Comment by phoniclynx** [comment]
They are brand new speakers yes.

I have tried changing the alarm and adding a different time, but I left that in there, so that is probably causing the new error.

Looks like it was a mixture of the two things, the Cache was confusing everything. Seems like it is updating it correctly now when I run it.

**Comment by duncan3dc** [comment]
Yes the cache is something that is much better in version 2.0, as I've had problems like this myself.

If you clear the cache now then you should be ok again until you add more devices
