### ISSUE TITLE
v2.0.2 & php 7.1

### ISSUE THREAD

**Issue by Rello** [duncan3dc/sonos#87]
Hey,

thank you for your library.
I have the issue that I am on php 7.0
which brings me back to sonos 1.9
but for this, http://duncan3dc.github.io/sonos/ is not available - neither is APIDocumentation

any suggestion to work without 7.1?

```
- duncan3dc/sonos 2.0.2 requires php ^7.1 -> your PHP version (7.0.30) does not satisfy that requirement.
- duncan3dc/sonos 2.0.1 requires php ^7.1 -> your PHP version (7.0.30) does not satisfy that requirement.
- duncan3dc/sonos 2.0.0 requires php ^7.1 -> your PHP version (7.0.30) does not satisfy that requirement.
```

**Comment by duncan3dc** [comment]
Hi there, thanks for your interest in the library

The docs for version 1.9 are still available, for example [here](https://github.com/duncan3dc/sonos/blob/78f106970b435f3c617e548e70424d6b4c4d1198/setup.md) is the old set up page.

You can view all of the pages via GitHub, or if you've got Jekyll installed you can generate a local version of the 1.9 docs:
```sh
git clone github.com:duncan3dc/sonos --branch=gh-pages /tmp/sonos-docs && \
    cd /tmp/sonos-docs && \
    git checkout 78f106970b435f3c617e548e70424d6b4c4d1198 && \
    jekyll serve
```

PHP 7.0 will only be receiving security fixes for a [few more months](http://php.net/supported-versions.php), so you consider upgrading to PHP 7.1 or PHP 7.2 as soon as possible.

I hope that helps!

**Comment by Rello** [comment]
thank you for your quick response.
...I am developing on a raspberry, which is still on 7.0...

my PHPStorm autocompletion seems to do the job for now on 1.9.
I am working on a Sonos-Integration for Nextcloud->Audioplayer
lets see how it will work out.
https://github.com/Rello/audioplayer
