### ISSUE TITLE
proposed changes envisaged for play pause next and previous:

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#9]
test on the play command if the sonos is not already in play or pause , and there was a few things to read.
idem for next and previous

**Comment by duncan3dc** [comment]
For the play stuff I would rather leave that to the calling code. There's a performance penalty for every soap call to the devices, and depending on the network conditions this could make things a lot less responsive.

I'll give it some thought though. Maybe we could catch an error on play, and then check the status, and ignore the error if the device is now playing

**Comment by 889laurent** [comment]
this is the best idea to avoid cluttering the network

**Comment by duncan3dc** [comment]
I've added this in 8758526a527d4b2de327a06b0af2906526609b15 now, I'll be tagging a new release a little bit later

**Comment by 889laurent** [comment]
Thanks

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo2015e6cff5]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1548667]                                                                                                      [cid:devdurable2b9773]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 12 mars 2015 à 21:29, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


I've added this in 8758526<https://github.com/duncan3dc/sonos/commit/8758526a527d4b2de327a06b0af2906526609b15> now, I'll be tagging a new release a little bit later

**Comment by 889laurent** [comment]
I think of seek second is a good idea but if you want to retreive a old position of a track the format hh:mm:ss is better

Cordialement
Laurent MARIO


Laurent MARIO Directeur Technique

  [cid:logo2015ad18ad]
________________________________

tel fixe: +33 4 93 23 27 27 télécopie: +33 4 93 23 27 20  tel direct: +33 4 93 23 27 21 mobile: +33 6 83 81 26 35 mail: laurent.MARIO@valtinee.fr

Route Départementale 2205 Lieu dit la Sorbière 06420 SAINT SAUVEUR SUR TINEE

________________________________

Ce mail a été envoyé depuis la societé VALTINEE. Si ce mail ne vous concerne pas, merci de le renvoyer a son expéditeur et de le détruire. L'ensemble de ce mail et de ses pièces jointes sont la propriété exclusive de l'entreprise VALTINEE. Tout usage non autorisé est strictement interdit.

Notre Entreprise, en complément de sa certification ISO 9001 (qualité) et ISO 14001 (environement), a été certifiée pour sa démarche sécurité OHSAS 18001  par CERTIBAT<http://www.certibat.fr>

Nous adhérons aux fédérations du TP<http://www.fntp.fr/> ,du batiment<http://www.ffbatiment.fr/> et du syndicat du  Béton Prêt a l'emploi<http://www.snbpe.org/>


[cid:picture1340851]                                                                                                      [cid:devdurable42d9c1]

 Issa Nissa<http://www.ogcnice.fr/> (*Allez NICE)                                  Pensez à l'environnement et n'imprimez ce mail que si nécessaire.



Le 12 mars 2015 à 21:29, Craig Duncan <notifications@github.com<mailto:notifications@github.com>> a écrit :


I've added this in 8758526<https://github.com/duncan3dc/sonos/commit/8758526a527d4b2de327a06b0af2906526609b15> now, I'll be tagging a new release a little bit later
