### ISSUE TITLE
New official Sonos API

### ISSUE THREAD

**Issue by Liver64** [duncan3dc/sonos#92]
Hi Craig. Not sure If you have noticed that Sonos released their API now for free. Do you have any plans to investigate? So far as i‘m informed the „old“ Interface will be turned off after a certain overlapping period. 
Thanks for your feedback, Oliver

**Comment by duncan3dc** [comment]
Hi Oliver,

Yes I've joined the developer program and I will be evaluating how to take this library forward.

I've not heard anything about them dropping their UPnP support, and I would be surprised if that's the case, but I'll be keeping an eye on developments

**Comment by tobiaskluge** [comment]
Hi Craig,

Just in case you need some data or code, we've put some php library code for the newa pi at https://github.com/hubwareHouse/sonos . But not yet finished.

Greetings, Tobias

**Comment by duncan3dc** [comment]
Hi @tobiaskluge, that's great.

I've started work on a separate library at https://github.com/duncan3dc/sonos-cloud
And I'll be converging the two over time so that you can do the same actions (as Sonos adds more to their cloud API) and choose whether you do it over the cloud or locally
