### ISSUE TITLE
Can't send an interupt call when rooms are grouped

### ISSUE THREAD

**Issue by phoniclynx** [duncan3dc/sonos#94]
When sending the command to interrupt the stream / TV / playlist when rooms are grouped or in party mode the script fails with the error:
`Fatal error: Uncaught duncan3dc\Sonos\Exceptions\SoapException: UPnPError: 701 in /var/www/html/vendor/duncan3dc/sonos/src/Devices/Device.php:152 Stack trace: #0 /var/www/html/vendor/duncan3dc/sonos/src/Speaker.php(86): duncan3dc\Sonos\Devices\Device->soap('AVTransport', 'Pause', Array) #1 /var/www/html/vendor/duncan3dc/sonos/src/Controller.php(719): duncan3dc\Sonos\Speaker->soap('AVTransport', 'Pause', Array) #2 /var/www/html/vendor/duncan3dc/sonos/src/Controller.php(188): duncan3dc\Sonos\Controller->soap('AVTransport', 'Pause') #3 /var/www/html/vendor/duncan3dc/sonos/src/Controller.php(589): duncan3dc\Sonos\Controller->pause() #4 /var/www/html/vendor/duncan3dc/sonos/src/Controller.php(677): duncan3dc\Sonos\Controller->exportState() #5 /var/www/html/sonoscontroller.php(112): duncan3dc\Sonos\Controller->interrupt(Object(smb)) #6 /var/www/html/index.php(1207): sonosDoorBell() #7 /var/www/html/index.php(87): sonos::doorbell() #8 {main} thrown in /var/www/html/vendor/duncan3dc/sonos/src/Devices/Device.php on line 152`

**Comment by phoniclynx** [comment]
Please help... this is preventing my code from running properly as it causes a stop error.

**Comment by duncan3dc** [comment]
Hi @phoniclynx, I'm a bit busy with paid work this month, but I should have some time to investigate your problem in November.

**Comment by duncan3dc** [comment]
I'm unable to reproduce this problem, when playing a track from a local music server, with 3 rooms grouped, I can send the `interrupt()` to any controller and it works correctly.

Is there something different about your set up? What music source are you using? Is the music already playing when you send the interrupt? Does it fail occasionally or all the time?

If you're able to reproduce the problem, can you [turn on logging](http://duncan3dc.github.io/sonos/setup/logging/) and post the results to a gist then link them here?
