### ISSUE TITLE
I've got a fatal error when installing latest code

### ISSUE THREAD

**Issue by freeyland** [duncan3dc/sonos#95]
My code:
<?php
require_once __DIR__ . "/vendor/autoload.php";

use duncan3dc\Sonos\Network;

$devices = new \duncan3dc\Sonos\Devices\Discovery();
$sonos = new Network($devices);

foreach($sonos->getSpeakers() as $_x ) {
var_dump($_x->getName(), $_x->getGroup());
}

Fatal error: Declaration of duncan3dc\Sonos\Speaker::updateGroup(): duncan3dc\Sonos\void must be compatible with duncan3dc\Sonos\Interfaces\SpeakerInterface::updateGroup(): duncan3dc\Sonos\Interfaces\void in /volume1/web/sonos/vendor/duncan3dc/sonos/src/Speaker.php on line 16

**Comment by duncan3dc** [comment]
Hi @freeyland, that looks like you're running it on an old unsupported version of PHP.
Can you check you're using at least version 7.1.0?

**Comment by freeyland** [comment]
Hi @duncan3dc ,
My version is  Version 7.0.30. WIll need to update my NAS or use docker :)
thnx
--

**Comment by duncan3dc** [comment]
That's great, good luck :+1:
